[package]
name = "leaven-workspace-docker"
description = "Leaven crate skeleton for leaven-workspace-docker."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
leaven-kernel = { workspace = true }
leaven-workspace = { workspace = true }
