# generated by datamodel-codegen:
#   filename:  common.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class LeavenCommonWireTypesV03(RootModel[Any]):
    root: Any = Field(..., title="Leaven Common Wire Types v0.3")


class StageAttemptId(RootModel[constr(pattern=r"^sa_[A-Za-z0-9_.:-]+$")]):
    root: constr(pattern=r"^sa_[A-Za-z0-9_.:-]+$")


class ResolvedSetId(RootModel[constr(pattern=r"^rset_[A-Za-z0-9_.:-]+$")]):
    root: constr(pattern=r"^rset_[A-Za-z0-9_.:-]+$")


class WatchId(RootModel[constr(pattern=r"^watch_[A-Za-z0-9_.:-]+$")]):
    root: constr(pattern=r"^watch_[A-Za-z0-9_.:-]+$")


class JsonValue(RootModel[Any]):
    root: Any


class StripAnnotationKeyword(Enum):
    title = "title"
    description = "description"
    default = "default"
    examples = "examples"
    deprecated = "deprecated"
    readOnly = "readOnly"
    writeOnly = "writeOnly"
    field_comment = "$comment"


class RefResolution(Enum):
    bundle_resolved = "bundle_resolved"
    inline_no_remote_refs = "inline_no_remote_refs"


class SchemaFingerprintAlgorithm(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["schema_fingerprint_algorithm"]
    canonicalization: Literal["RFC8785_JCS"]
    hash: Literal["sha256"]
    prefix: Literal["fp_schema_sha256_"]
    strip_annotation_keywords: list[StripAnnotationKeyword]
    ref_resolution: RefResolution


class DataClass1(Enum):
    public = "public"
    case_input = "case.input"
    case_target = "case.target"
    case_metadata = "case.metadata"
    candidate_output = "candidate.output"
    candidate_artifact = "candidate.artifact"
    workspace_file = "workspace.file"
    workspace_secret = "workspace.secret"
    scorer_private = "scorer.private"
    evaluator_private = "evaluator.private"
    optimizer_visible = "optimizer.visible"
    prompt_raw = "prompt.raw"
    completion_raw = "completion.raw"
    transcript_raw = "transcript.raw"
    human_review = "human.review"
    external_secret = "external.secret"


class DataFlowRule(Enum):
    union_all_inputs = "union_all_inputs"
    redaction_removes_content_not_receipt = "redaction_removes_content_not_receipt"
    projection_may_downgrade_only_if_registered = "projection_may_downgrade_only_if_registered"
    deny_overrides_allow = "deny_overrides_allow"
    literal_defaults_public = "literal_defaults_public"


class EvidenceVisibility(Enum):
    none = "none"
    score_only = "score_only"
    score_and_feedback = "score_and_feedback"
    public_only = "public_only"
    summary_only = "summary_only"
    trace_refs = "trace_refs"
    full = "full"
    operator_only = "operator_only"


class Replayability(Enum):
    pure_read = "pure_read"
    fully_managed = "fully_managed"
    boundary_managed = "boundary_managed"
    has_declared_external_effects = "has_declared_external_effects"
    has_untracked_external_effects = "has_untracked_external_effects"


class VisibilityClass(Enum):
    public = "public"
    optimizer_visible = "optimizer_visible"
    reflector_visible = "reflector_visible"
    evaluator_only = "evaluator_only"
    operator_only = "operator_only"
    private = "private"
    redacted = "redacted"


class TraceVisibility(Enum):
    summary = "summary"
    redacted_prompt = "redacted_prompt"
    redacted_completion = "redacted_completion"
    redacted_transcript = "redacted_transcript"
    operator_only = "operator_only"
    full = "full"


class ErrorCode(Enum):
    token_invalid = "token_invalid"
    token_expired = "token_expired"
    token_revoked = "token_revoked"
    capability_denied = "capability_denied"
    budget_exceeded = "budget_exceeded"
    quota_exceeded = "quota_exceeded"
    hidden_partition_violation = "hidden_partition_violation"
    data_class_violation = "data_class_violation"
    schema_validation_failed = "schema_validation_failed"
    stage_runtime_error = "stage_runtime_error"
    precondition_failed = "precondition_failed"
    revision_stale = "revision_stale"
    rate_limited = "rate_limited"
    cancelled = "cancelled"
    timeout = "timeout"
    provider_policy_denied = "provider_policy_denied"
    provider_error = "provider_error"
    workspace_policy_denied = "workspace_policy_denied"
    path_denied = "path_denied"
    sandbox_denied = "sandbox_denied"
    watch_closed = "watch_closed"
    internal_error = "internal_error"
    extension_error = "extension_error"


class CandidateRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["candidate"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^cand_[A-Za-z0-9_.:-]+$")


class ProposalRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["proposal"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^prop_[A-Za-z0-9_.:-]+$")


class ProposalBatchRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["proposal_batch"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^pb_[A-Za-z0-9_.:-]+$")


class AssessmentRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["assessment"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^assess_[A-Za-z0-9_.:-]+$")


class CaseRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["case"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^case_[A-Za-z0-9_.:-]+$")


class EvaluationRequestRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["evaluation_request"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^evalreq_[A-Za-z0-9_.:-]+$")


class EvaluationAttemptRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["evaluation_attempt"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^evalatt_[A-Za-z0-9_.:-]+$")


class WorkspaceRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["workspace"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    id: constr(pattern=r"^ws_[A-Za-z0-9_.:-]+$")
    snapshot_fingerprint: constr(pattern=r"^fp_[a-z0-9_]+_[A-Za-z0-9_.:-]+$") | None = None


class InfoRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["external"]
    namespace: str
    id: str
    schema_fingerprint: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$") | None = None


class ReceiptRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["receipt"]
    id: constr(
        pattern=r"^(qrec|caseread|wsread|lmrec|agentrec|execrec|humanrec|wrec|chargerec|valrec|watchrec)_[A-Za-z0-9_.:-]+$"
    )
    fingerprint: constr(pattern=r"^fp_[a-z0-9_]+_[A-Za-z0-9_.:-]+$") | None = None


class BlobRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["blob_ref"]
    id: constr(pattern=r"^blob_[A-Za-z0-9_.:-]+$")
    sha256: constr(pattern=r"^[a-f0-9]{64}$")
    bytes: conint(ge=0)
    media_type: str | None = None
    uri: constr(pattern=r"^(leaven-blob|file|https?)://.+$") | None = None
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]


class TraceRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: constr(pattern=r"^[a-z][a-z0-9_.:-]*$")
    id: str
    visibility: TraceVisibility
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = None
    receipt: (
        common_schema.ReceiptRef1
        | constr(
            pattern=r"^(qrec|caseread|wsread|lmrec|agentrec|execrec|humanrec|wrec|chargerec|valrec|watchrec)_[A-Za-z0-9_.:-]+$"
        )
        | None
    ) = None


class Cost(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """
    input_tokens: conint(ge=0) | None = None
    output_tokens: conint(ge=0) | None = None
    lm_calls: conint(ge=0) | None = None
    agent_calls: conint(ge=0) | None = None
    sandbox_calls: conint(ge=0) | None = None
    metric_calls: conint(ge=0) | None = None
    human_review_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """
    wall_ms: conint(ge=0) | None = None


class Kind(Enum):
    text = "text"
    json = "json"
    blob_ref = "blob_ref"
    structured = "structured"
    agent_session = "agent_session"
    workspace_diff = "workspace_diff"


class OutputRecord(BaseModel):
    """
    Required reportable output for every successful score.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    summary: constr(max_length=16000) | None = None
    value: Any | None = None
    blob_ref: BlobRef | None = None
    visibility: VisibilityClass
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]
    trace_refs: list[TraceRef] | None = None


class Score(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: float
    metrics: dict[str, float] | None = None
    output: OutputRecord
    uncertainty: float | None = None
    metadata: dict[str, Any] | None = None


class Reason(Enum):
    not_visible = "not_visible"
    case_target_hidden = "case_target_hidden"
    hidden_partition = "hidden_partition"
    evidence_visibility = "evidence_visibility"
    data_class_forbidden = "data_class_forbidden"
    path_denied = "path_denied"
    workspace_secret = "workspace_secret"
    count_policy = "count_policy"
    budget_policy = "budget_policy"
    provider_policy = "provider_policy"
    token_scope = "token_scope"
    extension_policy = "extension_policy"
    schema_policy = "schema_policy"
    unknown = "unknown"


class Redaction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    reason: Reason
    policy_fingerprint: constr(pattern=r"^fp_policy_sha256_[A-Za-z0-9_-]+$") | None = None
    public_reason: str | None = None
    audit_reason: str | None = None


class PlanError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: ErrorCode
    message: str
    op: str | None = None
    path: constr(pattern=r"^(|/.*)$") | None = None
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    receipt: (
        common_schema.ReceiptRef1
        | constr(
            pattern=r"^(qrec|caseread|wsread|lmrec|agentrec|execrec|humanrec|wrec|chargerec|valrec|watchrec)_[A-Za-z0-9_.:-]+$"
        )
        | None
    ) = None
    retryable: bool | None = None
    details: Any | None = None


class Status(Enum):
    passed = "passed"
    failed = "failed"


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    message: str


class ValidationReceipt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    receipt: common_schema.ReceiptRef1 | constr(
        pattern=r"^(qrec|caseread|wsread|lmrec|agentrec|execrec|humanrec|wrec|chargerec|valrec|watchrec)_[A-Za-z0-9_.:-]+$"
    )
    schema_fingerprint: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$") | None = None
    status: Status
    errors: list[Error] | None = None


class ExtensionObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["extension"]
    namespace: constr(pattern=r"^[a-z][a-z0-9_.:-]*$")
    op: constr(pattern=r"^[a-z][a-z0-9_.:-]*$")
    schema_fingerprint: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    payload: Any


class OutputContract1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["final_message"]
    max_bytes: conint(ge=1) | None = None


class OutputContract2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["json_schema"]
    schema_fingerprint: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    schema_: Any | None = Field(None, alias="schema")


class OutputContract3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["files"]
    paths: list[str] = Field(..., min_length=1)
    max_bytes: conint(ge=1) | None = None


class OutputContract4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["workspace_diff"]
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")
    max_bytes: conint(ge=1) | None = None
