# generated by datamodel-codegen:
#   filename:  leaven.stage_payloads.v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr

from . import common_schema


class ReflectiveExample(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    case: common_schema.CaseId | common_schema.CaseRef1 | None = None
    input: Any
    output: Any
    score: common_schema.Score
    feedback: str | None = None
    side_info: Any | None = None
    source_refs: list[
        common_schema.CandidateRef
        | common_schema.ProposalRef
        | common_schema.ProposalBatchRef
        | common_schema.AssessmentRef
        | common_schema.EvaluationRequestRef
        | common_schema.EvaluationAttemptRef
        | common_schema.InfoRef1
    ]
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]
    evidence_visibility: common_schema.EvidenceVisibility | None = None


class Severity(Enum):
    low = "low"
    medium = "medium"
    high = "high"
    blocking = "blocking"


class FailureMode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: str
    description: str
    severity: Severity | None = None
    source_refs: (
        list[
            common_schema.CandidateRef
            | common_schema.ProposalRef
            | common_schema.ProposalBatchRef
            | common_schema.AssessmentRef
            | common_schema.EvaluationRequestRef
            | common_schema.EvaluationAttemptRef
            | common_schema.InfoRef1
        ]
        | None
    ) = None


class SurfaceSuggestion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")
    part_label: str | None = None
    diagnosis: str
    suggested_direction: str | None = None
    constraints: list[str] | None = None
    source_refs: (
        list[
            common_schema.CandidateRef
            | common_schema.ProposalRef
            | common_schema.ProposalBatchRef
            | common_schema.AssessmentRef
            | common_schema.EvaluationRequestRef
            | common_schema.EvaluationAttemptRef
            | common_schema.InfoRef1
        ]
        | None
    ) = None


class ReflectionResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Literal["reflection_result"]
    summary: str
    failure_modes: list[FailureMode] | None = None
    surface_suggestions: list[SurfaceSuggestion] | None = None
    negative_constraints: list[str] | None = None
    positive_constraints: list[str] | None = None
    source_refs: list[
        common_schema.CandidateRef
        | common_schema.ProposalRef
        | common_schema.ProposalBatchRef
        | common_schema.AssessmentRef
        | common_schema.EvaluationRequestRef
        | common_schema.EvaluationAttemptRef
        | common_schema.InfoRef1
    ]
    read_receipts: list[common_schema.ReceiptId | common_schema.ReceiptRef1]
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]
    confidence: confloat(ge=0.0, le=1.0) | None = None


class ReflectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Literal["reflector"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    base_revision: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$")
    parent: common_schema.CandidateId | common_schema.CandidateRef1
    part: Any | None = None
    part_label: str | None = None
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$") | None = None
    examples: list[ReflectiveExample]
    source_refs: list[
        common_schema.CandidateRef
        | common_schema.ProposalRef
        | common_schema.ProposalBatchRef
        | common_schema.AssessmentRef
        | common_schema.EvaluationRequestRef
        | common_schema.EvaluationAttemptRef
        | common_schema.InfoRef1
    ]
    attempt_index: conint(ge=0, le=1000) | None = None
    target_safety: Literal["target_safe_projection"]
    query_policy_fingerprint: constr(pattern=r"^fp_[a-z0-9_]+_[A-Za-z0-9_.:-]+$") | None = None
    capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$")


class AllowedEffect(Enum):
    create = "create"
    change = "change"
    change_from_workspace_diff = "change_from_workspace_diff"
    change_from_agent_session = "change_from_agent_session"


class ProposeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Literal["proposer"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    base_revision: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$")
    parent: common_schema.CandidateId | common_schema.CandidateRef1
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$") | None = None
    reflection_result: ReflectionResult
    allowed_effects: list[AllowedEffect]
    allowed_change_schemas: list[constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")] | None = None
    source_refs: (
        list[
            common_schema.CandidateRef
            | common_schema.ProposalRef
            | common_schema.ProposalBatchRef
            | common_schema.AssessmentRef
            | common_schema.EvaluationRequestRef
            | common_schema.EvaluationAttemptRef
            | common_schema.InfoRef1
        ]
        | None
    ) = None
    query_policy_fingerprint: constr(pattern=r"^fp_[a-z0-9_]+_[A-Za-z0-9_.:-]+$") | None = None
    capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$")


class RunnerRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Literal["runner"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    candidate: common_schema.CandidateId | common_schema.CandidateRef1
    case: common_schema.CaseId | common_schema.CaseRef1
    case_input: Any
    target_forbidden: Literal[True]


class ScoreContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Literal["scorer"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    evaluation_request_id: constr(pattern=r"^evalreq_[A-Za-z0-9_.:-]+$")
    candidate: common_schema.CandidateId | common_schema.CandidateRef1
    case: common_schema.CaseId | common_schema.CaseRef1
    output: common_schema.OutputRecord
    target_handle: common_schema.CaseId | common_schema.CaseRef1 | None = None
    capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$")


class JudgeContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Literal["judge"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    left: common_schema.CandidateId | common_schema.CandidateRef1
    right: common_schema.CandidateId | common_schema.CandidateRef1
    case: common_schema.CaseId | common_schema.CaseRef1 | None = None
    outputs: list[common_schema.OutputRecord]
    rubric: Any | None = None
    capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$")


class CallbackRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Literal["callback"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    event: Any
    payload_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$")


class Role(Enum):
    artifact_adapter = "artifact_adapter"
    dataset_adapter = "dataset_adapter"


class AdapterRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.stage_payloads.v1"]
    role: Role
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    payload_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    payload: Any
    capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$")


class LeavenStagePayloadsV1V03(
    RootModel[
        ReflectRequest
        | ReflectionResult
        | ProposeRequest
        | RunnerRequest
        | ScoreContext
        | JudgeContext
        | CallbackRequest
        | AdapterRequest
    ]
):
    root: (
        ReflectRequest
        | ReflectionResult
        | ProposeRequest
        | RunnerRequest
        | ScoreContext
        | JudgeContext
        | CallbackRequest
        | AdapterRequest
    ) = Field(..., title="Leaven Stage Payloads v1 v0.3")
    """
    Role-specific payloads. Reflection and proposal are separate cognitive stages; ReflectionResult bridges them.
    """
