# generated by datamodel-codegen:
#   filename:  leaven.capability.v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr

from . import common_schema


class Kind(Enum):
    run_engine = "run_engine"
    operator = "operator"
    remote_control_plane = "remote_control_plane"


class Issuer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    id: str


class ExpiryBehavior(Enum):
    drain_inflight_no_new_ops = "drain_inflight_no_new_ops"
    cancel_inflight = "cancel_inflight"
    renew_required_before_long_call = "renew_required_before_long_call"


class Role(Enum):
    runner = "runner"
    scorer = "scorer"
    reflector = "reflector"
    proposer = "proposer"
    judge = "judge"
    callback = "callback"
    artifact_adapter = "artifact_adapter"
    dataset_adapter = "dataset_adapter"


class Subject1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["stage_call"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    role: Role


class Subject2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["evaluation_stage_call"]
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")
    evaluation_request_id: constr(pattern=r"^evalreq_[A-Za-z0-9_.:-]+$")
    evaluator: str | None = None


class Subject3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["operator"]
    principal: str


class TokenBinding1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["opaque_lookup"]
    token_id: constr(pattern=r"^ltok_[A-Za-z0-9_.:-]+$")
    lookup_audience: str | None = None


class Alg(Enum):
    EdDSA = "EdDSA"
    ES256 = "ES256"


class TokenBinding2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["signed_jwt"]
    alg: Alg
    kid: str


class TokenBinding3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["mtls_bound"]
    certificate_fingerprint: constr(pattern=r"^fp_[a-z0-9_]+_[A-Za-z0-9_.:-]+$")


class Mode(Enum):
    none = "none"
    issuer_epoch = "issuer_epoch"
    online_lookup = "online_lookup"
    crl = "crl"


class Check(Enum):
    on_authenticate = "on_authenticate"
    on_every_request = "on_every_request"
    on_long_call_boundary = "on_long_call_boundary"


class RevocationPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Mode
    revocation_epoch: conint(ge=0) | None = None
    revocation_list_uri: str | None = None
    check: Check


class Mode1(Enum):
    none = "none"
    renew_before_expiry = "renew_before_expiry"
    refresh_token = "refresh_token"


class RenewalPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Mode1
    max_extensions: conint(ge=0) | None = None
    max_total_lifetime_s: conint(ge=1) | None = None
    renewal_audience: str | None = None


class AggregateBudgets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_total_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """
    max_lm_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """
    max_agent_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """
    max_human_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """
    max_wall_ms: conint(ge=0) | None = None
    max_concurrent_calls: conint(ge=0) | None = None
    max_plan_nodes: conint(ge=1) | None = None
    max_materialized_bytes: conint(ge=0) | None = None


class Profile(Enum):
    trusted_local_operator = "trusted_local_operator"
    managed_sandbox = "managed_sandbox"
    package_scorer = "package_scorer"
    remote_untrusted = "remote_untrusted"
    custom = "custom"


class Network(Enum):
    deny = "deny"
    leaven_endpoint_only = "leaven_endpoint_only"
    allowlist = "allowlist"
    unrestricted = "unrestricted"


class Subprocess(Enum):
    deny = "deny"
    deny_except_sandbox_exec = "deny_except_sandbox_exec"
    allow = "allow"


class Filesystem(Enum):
    workspace_handles_only = "workspace_handles_only"
    project_readonly = "project_readonly"
    unrestricted = "unrestricted"


class ByoEffects(Enum):
    forbidden = "forbidden"
    declared_only = "declared_only"
    allowed_untracked = "allowed_untracked"


class ExecutionPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile: Profile
    network: Network
    subprocess: Subprocess
    filesystem: Filesystem
    byo_effects: ByoEffects
    allowlist: list[str] | None = None


class DelegationPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    may_delegate: bool
    max_depth: conint(ge=0)
    must_attenuate: bool
    allowed_actions: list[constr(pattern=r"^[a-z][a-z0-9_.:-]*$")] | None = None


class Resource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    run: constr(pattern=r"^run_[A-Za-z0-9_.:-]+$") | None = None
    runs: list[constr(pattern=r"^run_[A-Za-z0-9_.:-]+$")] | None = None
    run_set: str | None = None
    evaluation_request_id: constr(pattern=r"^evalreq_[A-Za-z0-9_.:-]+$") | None = None
    resolved_set: constr(pattern=r"^rset_[A-Za-z0-9_.:-]+$") | None = None
    candidate_ids: list[common_schema.CandidateId | common_schema.CandidateRef1] | None = None
    case_ids: list[common_schema.CaseId | common_schema.CaseRef1] | None = None
    workspace_ids: list[common_schema.WorkspaceId | common_schema.WorkspaceRef1] | None = None
    lm_pool: str | None = None
    runtime_pool: str | None = None
    sandbox_pool: str | None = None
    namespace: str | None = None


class CaseField(Enum):
    input = "input"
    target = "target"
    metadata = "metadata"


class ForbiddenCaseField(Enum):
    input = "input"
    target = "target"
    metadata = "metadata"


class Partition(Enum):
    train = "train"
    validation = "validation"
    test = "test"
    diagnostic = "diagnostic"
    custom = "custom"


class VisibilityClass(Enum):
    public = "public"
    hidden = "hidden"


class TargetEgress(Enum):
    none = "none"
    trusted_model_only = "trusted_model_only"
    operator_approved = "operator_approved"
    unrestricted = "unrestricted"


class CountPolicy(Enum):
    exact = "exact"
    bucketed = "bucketed"
    redacted = "redacted"
    denied = "denied"


class RevisionWindow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$") | None = None
    max: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$") | None = None


class RawPromptLogging(Enum):
    none = "none"
    redacted = "redacted"
    full = "full"


class RawCompletionLogging(Enum):
    none = "none"
    redacted = "redacted"
    full = "full"


class Effect(Enum):
    create = "create"
    change = "change"
    change_from_workspace_diff = "change_from_workspace_diff"
    change_from_agent_session = "change_from_agent_session"


class AssessmentShape(Enum):
    independent = "independent"
    pairwise = "pairwise"
    listwise = "listwise"


class Granularity(Enum):
    aggregate = "aggregate"
    per_case = "per_case"


class Constraints(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    queries: list[str] | None = None
    fields: list[str] | None = None
    case_fields: list[CaseField] | None = None
    forbidden_case_fields: list[ForbiddenCaseField] | None = None
    partitions: list[Partition] | None = None
    visibility_classes: list[VisibilityClass] | None = None
    target_egress: TargetEgress | None = None
    allowed_input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = None
    forbidden_input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = (
        None
    )
    evidence_visibility: common_schema.EvidenceVisibility | None = None
    count_policy: CountPolicy | None = None
    revision_window: RevisionWindow | None = None
    model_roles: list[str] | None = None
    models: list[str] | None = None
    purposes: list[str] | None = None
    raw_prompt_logging: RawPromptLogging | None = None
    raw_completion_logging: RawCompletionLogging | None = None
    raw_transcript_visibility: common_schema.EvidenceVisibility | None = None
    workspace_ops: list[str] | None = None
    deny_paths: list[str] | None = None
    allow_paths: list[str] | None = None
    allowed_commands: list[str] | None = None
    effects: list[Effect] | None = None
    allowed_surfaces: list[constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")] | None = None
    change_schemas: list[constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")] | None = None
    may_apply: bool | None = None
    assessment_shapes: list[AssessmentShape] | None = None
    granularity: Granularity | None = None
    allowed_candidates: list[common_schema.CandidateId | common_schema.CandidateRef1] | None = None
    allowed_cases: list[common_schema.CaseId | common_schema.CaseRef1] | None = None
    namespaces: list[str] | None = None
    ops: list[str] | None = None
    schemas: list[constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")] | None = None


class Limits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """
    max_calls: conint(ge=0) | None = None
    max_concurrent: conint(ge=0) | None = None
    timeout_s: conint(ge=1) | None = None
    max_rows: conint(ge=0) | None = None
    max_materialized_bytes: conint(ge=0) | None = None


class Grant(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: constr(pattern=r"^[a-z][a-z0-9_.:-]*$")
    resource: Resource
    constraints: Constraints
    limits: Limits | None = None


class LeavenCapabilityV1V03(BaseModel):
    """
    Opaque bearer token resolves to this fingerprinted grant document. Cedar-shaped grants. Macaroon-shaped attenuation. Aggregate budgets. Token binding. Revocation and renewal semantics.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.capability.v1"]
    jti: constr(pattern=r"^jti_[A-Za-z0-9_.:-]+$")
    capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$")
    grant_fingerprint: constr(pattern=r"^fp_grant_sha256_[A-Za-z0-9_-]+$") | None = None
    policy_fingerprint: constr(pattern=r"^fp_policy_sha256_[A-Za-z0-9_-]+$")
    subject_fingerprint: constr(pattern=r"^fp_subject_sha256_[A-Za-z0-9_-]+$")
    parent_capability_fingerprint: constr(pattern=r"^fp_cap_sha256_[A-Za-z0-9_-]+$") | None = None
    issuer: Issuer
    subject: Subject1 | Subject2 | Subject3
    audience: list[constr(pattern=r"^leaven(\.[a-z0-9_.:-]+)*$")] = Field(..., min_length=1)
    issued_at: AwareDatetime
    not_before: AwareDatetime | None = None
    expires_at: AwareDatetime
    expiry_behavior: ExpiryBehavior | None = None
    token_binding: TokenBinding1 | TokenBinding2 | TokenBinding3
    revocation: RevocationPolicy | None = None
    renewal: RenewalPolicy | None = None
    budgets: AggregateBudgets
    execution_policy: ExecutionPolicy
    grants: list[Grant] = Field(..., min_length=1)
    delegation: DelegationPolicy
    mint_time_validation: list[str] | None = None
    metadata: dict[str, Any] | None = None
