# generated by datamodel-codegen:
#   filename:  leaven.watch.v1.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class DeferredWatchMarker(BaseModel):
    """
    watch.v1 is deferred from the v1 lock. Use finite diff queries via leaven.plan.v1 consistency.since_revision. A full watch spec is targeted for v1.1.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.watch.v1.deferred"]
    use_instead: Literal["leaven.plan.v1 consistency.since_revision"]
