# generated by datamodel-codegen:
#   filename:  leaven.plan.v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr

from . import common_schema, leaven_evidence_envelope_v1_schema


class Consistency1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["latest_at_start"]


class Consistency2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["at_revision"]
    revision: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$")


class Consistency3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["since_revision"]
    since: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$")
    until: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$") | None = None


class EvalMode1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["execute"]


class EvalMode2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["dry_run"]


class EvalMode3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["require_cached"]


class EvalMode4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["replay"]
    receipts: list[common_schema.ReceiptId | common_schema.ReceiptRef1] = Field(..., min_length=1)


class CommitPolicy1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["no_graph_writes"]


class OnStale(Enum):
    reject = "reject"
    allow_if_policy_allows = "allow_if_policy_allows"
    rebase_extension = "rebase_extension"


class CommitPolicy2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["graph_writes_atomic"]
    on_stale: OnStale


class OnFailure(Enum):
    stop = "stop"
    continue_ = "continue"


class CommitPolicy3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["graph_writes_sequential"]
    on_failure: OnFailure
    on_stale: OnStale


class Expr1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["literal"]
    value: Any
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = None


class Expr2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["var"]
    name: constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")


class Expr12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["refs_from_result"]
    from_: constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$") = Field(..., alias="from")


class PageRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limit: conint(ge=1, le=10000) | None = None
    cursor: constr(pattern=r"^cur_[A-Za-z0-9_.:-]+$") | None = None
    stable_order: bool | None = True


class GraphSource1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["by_candidate"]
    candidate: common_schema.CandidateId | common_schema.CandidateRef1


class GraphSource3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["by_proposal"]
    proposal: common_schema.ProposalId | common_schema.ProposalRef1


class GraphSource4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["by_proposal_batch"]
    proposal_batch: common_schema.ProposalBatchId | common_schema.ProposalBatchRef1


class GraphSource6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["recent_failures"]
    limit: conint(ge=1, le=1000)


class GraphSource7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["costs"]
    scope: Any


class GraphSource8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["events"]
    since_revision: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$") | None = None
    until_revision: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$") | None = None
    filter: Any | None = None


class GraphSource9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["candidate_tree"]
    root: common_schema.CandidateId | common_schema.CandidateRef1 | None = None
    depth: conint(ge=0) | None = None


class GraphStep4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["limit"]
    limit: conint(ge=0, le=100000)


class GraphEdge1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["parents"]


class GraphEdge2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["children"]


class GraphEdge3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["siblings"]


class GraphEdge4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["informed_by"]


class GraphEdge5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["informed"]


class GraphEdge6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["proposal_that_created"]


class GraphEdge7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["lineage"]
    depth: conint(ge=0) | None = None


class GraphEdge8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["descendants"]
    depth: conint(ge=0) | None = None


class GraphEdge10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["pairwise_assessments"]
    other: common_schema.CandidateId | common_schema.CandidateRef1


class Kind(Enum):
    independent = "independent"
    pairwise = "pairwise"
    listwise = "listwise"


class Predicate1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["eq"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["ne"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["gt"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["gte"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["lt"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["lte"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["contains"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["matches"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    value: Any


class Predicate9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["in"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    values: list[Any]


class Predicate10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["exists"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """


class Predicate11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["is_null"]
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """


class Direction(Enum):
    asc = "asc"
    desc = "desc"


class Nulls(Enum):
    first = "first"
    last = "last"


class SortKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    direction: Direction
    nulls: Nulls | None = None


class Projection1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["ids"]


class Projection2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["summary"]
    fields: list[constr(pattern=r"^(|/.*)$")] | None = None


class Projection5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["assessment_projection"]
    fields: list[constr(pattern=r"^(|/.*)$")] | None = None
    evidence_visibility: common_schema.EvidenceVisibility | None = None


class Projection6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["diff_projection"]
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")
    diff_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    left: common_schema.CandidateId | common_schema.CandidateRef1
    right: common_schema.CandidateId | common_schema.CandidateRef1


class ArtifactProjection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")
    projection_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    selector_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$") | None = None
    selector: Any | None = None
    max_bytes: conint(ge=1) | None = None
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = None


class Purpose(Enum):
    train = "train"
    validation = "validation"
    test = "test"
    diagnostic = "diagnostic"
    custom = "custom"


class IncludeEnum(Enum):
    input = "input"
    target = "target"
    metadata = "metadata"


class CaseQuery2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["load"]
    case: common_schema.CaseId | common_schema.CaseRef1
    include: list[IncludeEnum]
    projection_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$") | None = None


class EvaluationSetExpr1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["named"]
    name: str


class EvaluationSetExpr2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["cases"]
    cases: list[common_schema.CaseId | common_schema.CaseRef1] = Field(..., min_length=1)
    requires_partition_resolution: Literal[True]


class EvaluationSetExpr3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["tagged"]
    tag: str
    requires_partition_resolution: Literal[True]


class EvaluationSetExpr4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["recent"]
    limit: conint(ge=1)
    requires_partition_resolution: Literal[True]


class WorkspaceQuery1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["snapshot"]


class WorkspaceQuery2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["list"]
    path: str
    recursive: bool | None = None
    max_entries: conint(ge=1) | None = None


class WorkspaceQuery3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["read_file"]
    path: str
    max_bytes: conint(ge=1) | None = None
    expected_data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]


class WorkspaceQuery4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["stat"]
    path: str


class Algorithm(Enum):
    sha256 = "sha256"
    blake3 = "blake3"


class WorkspaceQuery5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["digest"]
    path: str
    algorithm: Algorithm


class WorkspaceQuery6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["git_log"]
    max_entries: conint(ge=1, le=1000) | None = None


class Against(Enum):
    seed = "seed"
    parent = "parent"
    baseline = "baseline"
    head = "head"


class WorkspaceQuery7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["git_diff"]
    against: Against
    max_bytes: conint(ge=1) | None = None


class WorkspaceQuery8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["git_status"]
    porcelain: bool | None = None


class WorkspaceQuery9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["capture_artifacts"]
    paths: list[str]
    max_bytes: conint(ge=1) | None = None


class LmContentPart1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["text"]
    text: str


class LmContentPart2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["tool_result"]
    tool_call_id: str
    content: str


class Role(Enum):
    system = "system"
    developer = "developer"
    user = "user"
    assistant = "assistant"
    tool = "tool"


class LmMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Role
    content: list[LmContentPart1 | LmContentPart2 | common_schema.ExtensionObject] = Field(
        ..., min_length=1
    )
    tool_call_id: str | None = None
    name: str | None = None


class LmTool(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]{0,63}$")
    description: str | None = None
    input_schema: Any
    requires_capability_action: constr(pattern=r"^[a-z][a-z0-9_.:-]*$") | None = None


class LmSampling(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    temperature: confloat(ge=0.0) | None = None
    top_p: confloat(ge=0.0, le=1.0) | None = None
    max_output_tokens: conint(ge=1) | None = None
    seed: int | None = None
    stop: list[str] | None = None


class LmOutputContract1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["final_message"]
    max_bytes: conint(ge=1) | None = None


class LmOutputContract2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["json_schema"]
    schema_fingerprint: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    schema_: Any | None = Field(None, alias="schema")


class CachePolicy(Enum):
    default = "default"
    require_cached = "require_cached"
    bypass = "bypass"
    record_only = "record_only"


class LmCompleteCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["lm_complete"]
    purpose: constr(pattern=r"^[a-z][a-z0-9_.:-]*$")
    model: str | None = None
    model_role: str | None = None
    messages: list[LmMessage] = Field(..., min_length=1)
    tools: list[LmTool] | None = None
    sampling: LmSampling | None = None
    output: LmOutputContract1 | LmOutputContract2
    provider_hints: dict[constr(pattern=r"^[a-z][a-z0-9_.:-]*$"), Any] | None = None
    cache_policy: CachePolicy | None = None
    input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]
    forbidden_input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = (
        None
    )


class Network(Enum):
    deny = "deny"
    leaven_endpoint_only = "leaven_endpoint_only"
    allowlist = "allowlist"
    unrestricted = "unrestricted"


class AgentToolPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allow_shell: bool | None = None
    allowed_tools: list[str] | None = None
    denied_tools: list[str] | None = None
    allowed_commands: list[str] | None = None
    deny_paths: list[str] | None = None
    network: Network | None = None


class Instructions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    system: str | None = None
    task: str


class Limits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    timeout_s: conint(ge=1) | None = None
    max_turns: conint(ge=1) | None = None
    max_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """


class AgentRunCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["agent_run"]
    runtime: str
    runtime_fingerprint: constr(pattern=r"^fp_runtime_sha256_[A-Za-z0-9_-]+$") | None = None
    workspace: common_schema.WorkspaceId | common_schema.WorkspaceRef1 | None = None
    instructions: Instructions
    tool_policy: AgentToolPolicy | None = None
    output: (
        common_schema.OutputContract1
        | common_schema.OutputContract2
        | common_schema.OutputContract3
        | common_schema.OutputContract4
    )
    limits: Limits | None = None
    input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]
    forbidden_input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = (
        None
    )


class StreamPolicy(Enum):
    buffer = "buffer"
    stream_updates = "stream_updates"
    blob_refs_only = "blob_refs_only"


class SandboxExecCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["sandbox_exec"]
    workspace: common_schema.WorkspaceId | common_schema.WorkspaceRef1
    argv: list[str] = Field(..., min_length=1)
    cwd: str | None = None
    env: dict[str, str] | None = None
    timeout_s: conint(ge=1)
    output: (
        common_schema.OutputContract1
        | common_schema.OutputContract2
        | common_schema.OutputContract3
        | common_schema.OutputContract4
    )
    stream_policy: StreamPolicy | None = None
    input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]
    forbidden_input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = (
        None
    )


class Mode(Enum):
    read_only = "read_only"
    copy_on_write = "copy_on_write"
    mutable_eval = "mutable_eval"


class Lifetime(Enum):
    plan = "plan"
    stage_call = "stage_call"
    manual_release = "manual_release"


class WorkspaceMaterializeCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["workspace_materialize"]
    candidate: common_schema.CandidateId | common_schema.CandidateRef1
    surface: str | None = None
    mode: Mode
    lifetime: Lifetime


class WorkspaceReleaseCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["workspace_release"]
    workspace: common_schema.WorkspaceId | common_schema.WorkspaceRef1
    force: bool | None = None


class HumanReviewCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["human_review"]
    queue: str
    prompt: str
    rubric: Any | None = None
    input_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]
    max_usd_micro: conint(ge=0) | None = None
    """
    Integer micro-dollars. No floating-point money.
    """


class ValueExpr1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["literal"]
    value: Any


class ValueExpr2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["var"]
    name: constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")


class ProposalEffectWrite3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["change_from_workspace_diff"]
    target: common_schema.CandidateId | common_schema.CandidateRef1
    workspace: common_schema.WorkspaceId | common_schema.WorkspaceRef1
    roots: list[str] | None = None
    parser: str | None = None
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")
    change_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")


class ProposalEffectWrite4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["change_from_agent_session"]
    target: common_schema.CandidateId | common_schema.CandidateRef1
    agent_receipt: common_schema.ReceiptId | common_schema.ReceiptRef1
    parser: str
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")
    change_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")


class Semantics(Enum):
    alternatives = "alternatives"
    sequence = "sequence"


class Kind7(Enum):
    sum_effect_receipts = "sum_effect_receipts"
    explicit = "explicit"
    none = "none"


class CostAttribution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind7
    cost: common_schema.Cost | None = None


class Assessment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    candidate: common_schema.CandidateId | common_schema.CandidateRef1 | None = None
    candidates: list[common_schema.CandidateId | common_schema.CandidateRef1] | None = None
    target: Any | None = None
    score: common_schema.Score
    preference: Any | None = None
    ranking: Any | None = None
    evidence: leaven_evidence_envelope_v1_schema.LeavenEvidenceEnvelopeV1V03
    read_receipts: list[common_schema.ReceiptId | common_schema.ReceiptRef1] | None = None
    effect_receipts: list[common_schema.ReceiptId | common_schema.ReceiptRef1] | None = None
    replayability: common_schema.Replayability
    cost_attribution: CostAttribution | None = None


class SubmitAssessmentsWrite(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["submit_assessments"]
    evaluation_request_id: constr(pattern=r"^evalreq_[A-Za-z0-9_.:-]+$")
    assessments: list[Assessment] = Field(..., min_length=1)


class Shape(Enum):
    independent = "independent"
    pairwise = "pairwise"
    listwise = "listwise"


class Granularity(Enum):
    aggregate = "aggregate"
    per_case = "per_case"


class Policy(Enum):
    apply_all = "apply_all"
    apply_first_valid = "apply_first_valid"
    apply_by_optimizer_policy = "apply_by_optimizer_policy"


class ApplyProposalBatchWrite(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["apply_proposal_batch"]
    proposal_batch: common_schema.ProposalBatchId | common_schema.ProposalBatchRef1
    policy: Policy


class EmitRunEventWrite(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["emit_run_event"]
    event_kind: constr(pattern=r"^[a-z][a-z0-9_.:-]*$")
    payload_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    payload: Any
    visibility: common_schema.VisibilityClass


class Precondition1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["candidate_exists"]
    candidate: common_schema.CandidateId | common_schema.CandidateRef1


class Precondition2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["candidate_identity"]
    candidate: common_schema.CandidateId | common_schema.CandidateRef1
    identity: constr(pattern=r"^artifact_sha256_[A-Za-z0-9_-]+$")


class Precondition3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["graph_revision_at_least"]
    revision: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$")


class Precondition4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["graph_revision_equals"]
    revision: constr(pattern=r"^rev_[A-Za-z0-9_.:-]+$")


class Precondition5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["assessment_exists"]
    assessment: common_schema.AssessmentId | common_schema.AssessmentRef1


class Precondition6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["receipt_exists"]
    receipt: common_schema.ReceiptId | common_schema.ReceiptRef1


class Expr5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["workspace_query"]
    workspace: common_schema.WorkspaceId | common_schema.WorkspaceRef1
    op: (
        WorkspaceQuery1
        | WorkspaceQuery2
        | WorkspaceQuery3
        | WorkspaceQuery4
        | WorkspaceQuery5
        | WorkspaceQuery6
        | WorkspaceQuery7
        | WorkspaceQuery8
        | WorkspaceQuery9
    )


class GraphStep3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["sort"]
    keys: list[SortKey]


class Projection3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["candidate_projection"]
    fields: list[constr(pattern=r"^(|/.*)$")] | None = None
    artifact: ArtifactProjection | None = None


class Projection4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["artifact_projection"]
    artifact: ArtifactProjection


class PlanOp2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["call"]
    name: constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")
    call: (
        LmCompleteCall
        | AgentRunCall
        | SandboxExecCall
        | WorkspaceMaterializeCall
        | WorkspaceReleaseCall
        | HumanReviewCall
        | common_schema.ExtensionObject
    )
    deps: list[constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")] | None = None
    idempotency_key: constr(pattern=r"^[A-Za-z0-9_.:-]{8,160}$")


class GraphStep5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["project"]
    projection: (
        Projection1
        | Projection2
        | Projection3
        | Projection4
        | Projection5
        | Projection6
        | common_schema.ExtensionObject
    )


class LeavenPlanIrV1V03(BaseModel):
    """
    One value IR family with Let/Call/Write. v0.3 pins path/template dialects, flattens query exprs, adds typed tool/LM/workspace/evaluation shapes, and separates reflection from proposal at payload level.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.plan.v1"]
    plan_id: constr(pattern=r"^[A-Za-z0-9_.:-]{8,160}$")
    consistency: Consistency1 | Consistency2 | Consistency3
    mode: EvalMode1 | EvalMode2 | EvalMode3 | EvalMode4
    ops: list[PlanOp1 | PlanOp2 | PlanOp3] = Field(..., min_length=1)
    return_: list[constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")] = Field(..., alias="return")
    commit: CommitPolicy1 | CommitPolicy2 | CommitPolicy3
    metadata: dict[str, Any] | None = None


class PlanOp1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["let"]
    name: constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")
    expr: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    deps: list[constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")] | None = None


class PlanOp3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["write"]
    name: constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")
    write: (
        SubmitProposalBatchWrite
        | SubmitAssessmentsWrite
        | RequestEvaluationWrite
        | ApplyProposalBatchWrite
        | EmitRunEventWrite
        | common_schema.ExtensionObject
    )
    preconditions: (
        list[
            leaven_plan_v1_schema.Precondition1
            | leaven_plan_v1_schema.Precondition2
            | leaven_plan_v1_schema.Precondition3
            | leaven_plan_v1_schema.Precondition4
            | leaven_plan_v1_schema.Precondition5
            | leaven_plan_v1_schema.Precondition6
            | leaven_plan_v1_schema.Precondition7
        ]
        | None
    ) = None
    deps: list[constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")] | None = None
    idempotency_key: constr(pattern=r"^[A-Za-z0-9_.:-]{8,160}$")


class Expr3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["graph_query"]
    source: (
        GraphSource1
        | GraphSource2
        | GraphSource3
        | GraphSource4
        | GraphSource5
        | GraphSource6
        | GraphSource7
        | GraphSource8
        | GraphSource9
        | common_schema.ExtensionObject
    )
    steps: list[GraphStep1 | GraphStep2 | GraphStep3 | GraphStep4 | GraphStep5] | None = None
    projection: (
        Projection1
        | Projection2
        | Projection3
        | Projection4
        | Projection5
        | Projection6
        | common_schema.ExtensionObject
    )
    page: PageRequest | None = None


class Expr4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["case_query"]
    query: CaseQuery1 | CaseQuery2


class Expr6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["project"]
    input: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    projection: (
        Projection1
        | Projection2
        | Projection3
        | Projection4
        | Projection5
        | Projection6
        | common_schema.ExtensionObject
    )


class Expr7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["filter"]
    input: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    predicate: (
        Predicate1
        | Predicate2
        | Predicate3
        | Predicate4
        | Predicate5
        | Predicate6
        | Predicate7
        | Predicate8
        | Predicate9
        | Predicate10
        | Predicate11
        | Predicate12
        | Predicate13
        | Predicate14
    )


class Expr8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["sort"]
    input: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    keys: list[SortKey]


class Expr9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["limit"]
    input: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    limit: conint(ge=0, le=100000)


class Expr10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["template"]
    dialect: Literal["leaven.mustache.strict.v1"]
    """
    Strict Mustache subset. Variables, dotted names, sections, inverted sections. No lambdas, partials, executable helpers, or custom filters.
    """
    template: str
    vars: dict[
        str,
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject,
    ]


class Expr11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["extract"]
    input: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    path: constr(pattern=r"^\$($|[.\[].*)")
    """
    RFC 9535 JSONPath, Leaven subset: root, child, bracket, index, slice, wildcard. No filters, scripts, functions, or implementation-defined extensions.
    """


class GraphSource2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["candidate_set"]
    filter: CandidateFilter | None = None


class GraphSource5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["assessment_set"]
    filter: AssessmentFilter | None = None


class GraphStep1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["traverse"]
    edge: (
        GraphEdge1
        | GraphEdge2
        | GraphEdge3
        | GraphEdge4
        | GraphEdge5
        | GraphEdge6
        | GraphEdge7
        | GraphEdge8
        | GraphEdge9
        | GraphEdge10
    )


class GraphStep2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["filter"]
    predicate: (
        Predicate1
        | Predicate2
        | Predicate3
        | Predicate4
        | Predicate5
        | Predicate6
        | Predicate7
        | Predicate8
        | Predicate9
        | Predicate10
        | Predicate11
        | Predicate12
        | Predicate13
        | Predicate14
    )


class GraphEdge9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["assessments"]
    filter: AssessmentFilter | None = None


class CandidateFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ids: list[common_schema.CandidateId | common_schema.CandidateRef1] | None = None
    predicate: (
        Predicate1
        | Predicate2
        | Predicate3
        | Predicate4
        | Predicate5
        | Predicate6
        | Predicate7
        | Predicate8
        | Predicate9
        | Predicate10
        | Predicate11
        | Predicate12
        | Predicate13
        | Predicate14
        | None
    ) = None


class AssessmentFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate: common_schema.CandidateId | common_schema.CandidateRef1 | None = None
    case: common_schema.CaseId | common_schema.CaseRef1 | None = None
    request: common_schema.EvaluationRequestId | common_schema.EvaluationRequestRef1 | None = None
    kind: Kind | None = None
    predicate: (
        Predicate1
        | Predicate2
        | Predicate3
        | Predicate4
        | Predicate5
        | Predicate6
        | Predicate7
        | Predicate8
        | Predicate9
        | Predicate10
        | Predicate11
        | Predicate12
        | Predicate13
        | Predicate14
        | None
    ) = None


class Predicate12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["and"]
    predicates: list[
        Predicate1
        | Predicate2
        | Predicate3
        | Predicate4
        | Predicate5
        | Predicate6
        | Predicate7
        | Predicate8
        | Predicate9
        | Predicate10
        | Predicate11
        | Predicate12
        | Predicate13
        | Predicate14
    ] = Field(..., min_length=1)


class Predicate13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["or"]
    predicates: list[
        Predicate1
        | Predicate2
        | Predicate3
        | Predicate4
        | Predicate5
        | Predicate6
        | Predicate7
        | Predicate8
        | Predicate9
        | Predicate10
        | Predicate11
        | Predicate12
        | Predicate13
        | Predicate14
    ] = Field(..., min_length=1)


class Predicate14(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["not"]
    predicate: (
        Predicate1
        | Predicate2
        | Predicate3
        | Predicate4
        | Predicate5
        | Predicate6
        | Predicate7
        | Predicate8
        | Predicate9
        | Predicate10
        | Predicate11
        | Predicate12
        | Predicate13
        | Predicate14
    )


class CaseQuery1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["resolve_set"]
    set: (
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    )
    purpose: Purpose


class EvaluationSetExpr5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["union"]
    sets: list[
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    ] = Field(..., min_length=1)


class EvaluationSetExpr6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["intersect"]
    sets: list[
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    ] = Field(..., min_length=1)


class EvaluationSetExpr7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["difference"]
    base: (
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    )
    subtract: (
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    )


class EvaluationSetExpr8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["sample"]
    base: (
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    )
    n: conint(ge=1)
    seed: int


class EvaluationSetExpr9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["stratified"]
    base: (
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    )
    by: constr(pattern=r"^(|/.*)$")
    """
    RFC 6901 JSON Pointer. Used for field refs and redaction paths.
    """
    per_bucket: conint(ge=1)
    seed: int


class ValueExpr3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["extract"]
    input: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    path: constr(pattern=r"^\$($|[.\[].*)")
    """
    RFC 9535 JSONPath, Leaven subset: root, child, bracket, index, slice, wildcard. No filters, scripts, functions, or implementation-defined extensions.
    """


class ProposalEffectWrite1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["create"]
    artifact_type: str
    artifact_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    artifact: ValueExpr1 | ValueExpr2 | ValueExpr3 | common_schema.ExtensionObject


class ProposalEffectWrite2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["change"]
    target: common_schema.CandidateId | common_schema.CandidateRef1
    surface_fingerprint: constr(pattern=r"^fp_surface_sha256_[A-Za-z0-9_-]+$")
    change_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    change: ValueExpr1 | ValueExpr2 | ValueExpr3 | common_schema.ExtensionObject


class Proposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    effect: (
        ProposalEffectWrite1 | ProposalEffectWrite2 | ProposalEffectWrite3 | ProposalEffectWrite4
    )
    causal: Any
    informed_by: (
        Expr1
        | Expr2
        | Expr3
        | Expr4
        | Expr5
        | Expr6
        | Expr7
        | Expr8
        | Expr9
        | Expr10
        | Expr11
        | Expr12
        | common_schema.ExtensionObject
    )
    annotations: ValueExpr1 | ValueExpr2 | ValueExpr3 | common_schema.ExtensionObject | None = None
    annotations_schema: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$") | None = None
    read_receipts: list[common_schema.ReceiptId | common_schema.ReceiptRef1] | None = None
    metadata: dict[str, Any] | None = None


class SubmitProposalBatchWrite(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["submit_proposal_batch"]
    semantics: Semantics
    proposals: list[Proposal] = Field(..., min_length=1)


class Request(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shape: Shape
    candidates: list[common_schema.CandidateId | common_schema.CandidateRef1] = Field(
        ..., min_length=1
    )
    set: (
        EvaluationSetExpr1
        | EvaluationSetExpr2
        | EvaluationSetExpr3
        | EvaluationSetExpr4
        | EvaluationSetExpr5
        | EvaluationSetExpr6
        | EvaluationSetExpr7
        | EvaluationSetExpr8
        | EvaluationSetExpr9
    )
    granularity: Granularity
    purpose: Purpose
    evaluator: str | None = None
    metadata: dict[str, Any] | None = None


class RequestEvaluationWrite(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["request_evaluation"]
    request: Request


class Precondition7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["schema_valid"]
    schema_fingerprint: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$")
    value: ValueExpr1 | ValueExpr2 | ValueExpr3 | common_schema.ExtensionObject


LeavenPlanIrV1V03.model_rebuild()
PlanOp1.model_rebuild()
PlanOp3.model_rebuild()
Expr3.model_rebuild()
Expr4.model_rebuild()
Expr6.model_rebuild()
Expr7.model_rebuild()
Expr8.model_rebuild()
Expr9.model_rebuild()
Expr10.model_rebuild()
Expr11.model_rebuild()
GraphSource2.model_rebuild()
GraphSource5.model_rebuild()
GraphStep1.model_rebuild()
GraphStep2.model_rebuild()
GraphEdge9.model_rebuild()
CandidateFilter.model_rebuild()
AssessmentFilter.model_rebuild()
Predicate12.model_rebuild()
Predicate13.model_rebuild()
Predicate14.model_rebuild()
CaseQuery1.model_rebuild()
EvaluationSetExpr5.model_rebuild()
EvaluationSetExpr6.model_rebuild()
EvaluationSetExpr7.model_rebuild()
EvaluationSetExpr8.model_rebuild()
EvaluationSetExpr9.model_rebuild()
