# generated by datamodel-codegen:
#   filename:  leaven.worker_protocol.v1.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class DeprecatedWorkerProtocolMarker(BaseModel):
    """
    Deprecated. Use leaven.acp_profile.v1.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.worker_protocol.v1.deprecated"]
    replacement: Literal["leaven.acp_profile.v1"]
