# generated by datamodel-codegen:
#   filename:  leaven.evidence_envelope.v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, constr

from . import common_schema


class Producer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluator_id: str | None = None
    evaluator_fingerprint: constr(pattern=r"^fp_[a-z0-9_]+_[A-Za-z0-9_.:-]+$") | None = None
    stage_call_id: constr(pattern=r"^sc_[A-Za-z0-9_.:-]+$")


class Public(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    feedback: str | None = None
    summary: str | None = None
    metrics: dict[str, float] | None = None
    trace_refs: list[common_schema.TraceRef] | None = None
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]


class Visibility(Enum):
    evaluator_only = "evaluator_only"
    operator_only = "operator_only"
    scorer_private = "scorer_private"


class Private(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    visibility: Visibility
    payload: Any | None = None
    payload_ref: common_schema.BlobRef | None = None
    payload_schema_fingerprint: constr(pattern=r"^fp_schema_sha256_[A-Za-z0-9_-]+$") | None = None
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")]


class RedactionPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    optimizer: common_schema.EvidenceVisibility
    reflector: common_schema.EvidenceVisibility
    operator: common_schema.EvidenceVisibility


class SourceReceipts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    read: list[common_schema.ReceiptId | common_schema.ReceiptRef1]
    effect: list[common_schema.ReceiptId | common_schema.ReceiptRef1]
    write: list[common_schema.ReceiptId | common_schema.ReceiptRef1] | None = None


class LeavenEvidenceEnvelopeV1V03(BaseModel):
    """
    Visibility-labeled evidence. Score.output is canonical reportable output; evidence explains and projects it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.evidence_envelope.v1"]
    target_derived: bool
    data_classes: list[DataClass1 | constr(pattern=r"^x\.[A-Za-z0-9_.:-]+$")] | None = None
    producer: Producer
    public: Public
    private: Private | None = None
    redaction_policy: RedactionPolicy
    source_receipts: SourceReceipts
    trace_refs: list[common_schema.TraceRef] | None = None
    replayability: common_schema.Replayability | None = None
    metadata: dict[str, Any] | None = None
