# generated by datamodel-codegen:
#   filename:  leaven.acp_profile.v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Transport(Enum):
    stdio_jsonrpc = "stdio_jsonrpc"
    unix_socket_jsonrpc = "unix_socket_jsonrpc"
    http_jsonrpc = "http_jsonrpc"
    websocket_jsonrpc = "websocket_jsonrpc"


class Auth(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token_env: Literal["LEAVEN_CAPABILITY_TOKEN"]
    endpoint_env: Literal["LEAVEN_ENDPOINT"]
    fingerprint_env: Literal["LEAVEN_CAPABILITY_FINGERPRINT"]
    http_header: Literal["Authorization: Bearer <token>"]
    authenticate_maps_to: Literal["leaven.capability.v1"]


class PermissionModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Literal["ACP session/request_permission"]
    answer: Literal["programmatic capability grant check"]
    denial: Literal["PlanError + Redaction"]


class ExtensionMethod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: constr(pattern=r"^leaven/[a-z0-9_.:-]+$")
    params_schema: str
    result_schema: str
    required_action: constr(pattern=r"^[a-z][a-z0-9_.:-]*$")
    produces_receipt: bool


class Backpressure(Enum):
    pause_worker = "pause_worker"
    drop_noncritical_updates = "drop_noncritical_updates"
    disconnect = "disconnect"


class FlowControl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounded_channel_required: Literal[True]
    default_max_inflight_updates: conint(ge=1)
    backpressure: Backpressure
    heartbeat_ms: conint(ge=1000) | None = None


class LeavenAcpProfileV1V03(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["leaven.acp_profile.v1"]
    base_protocol: Literal["agent-client-protocol"]
    pinned_acp_version: str
    transports: list[Transport] = Field(..., min_length=1)
    auth: Auth
    permission_model: PermissionModel | None = None
    extension_methods: list[ExtensionMethod] = Field(..., min_length=1)
    flow_control: FlowControl
