"""Generate Python typed records from the locked public-seam-v1 JSON Schemas.

Pipeline:
1. Run `preprocess_schemas.py` to normalize boolean schemas into the
   build/ directory.
2. Run `datamodel-codegen` against each preprocessed schema to produce
   a Python module under `src/leaven/_types/`.
3. Run `ruff format` over the generated output for consistency.

Skipped schemas (per `docs/specs/leaven_python.md` "What this spec does
not say"):
- `leaven.watch.v1.schema.json` — watch.v1 runtime is deferred from V1
- `leaven.worker_protocol.v1.schema.json` — deprecated in favor of ACP

Usage:
    just codegen
    # or
    uv run python codegen/generate_types.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # docs/specs/leaven_py/
SOURCE_SCHEMA_DIR = ROOT.parent / "public-seam-v1" / "schemas"
BUILD_DIR = ROOT / "build" / "schemas"
OUT_DIR = ROOT / "src" / "leaven" / "_types"

# Schemas we actively code-generate, with their target module names.
# Skipped: watch.v1 (deferred), worker_protocol.v1 (deprecated).
SCHEMA_TO_MODULE: dict[str, str] = {
    "common.schema.json": "common.py",
    "leaven.acp_profile.v1.schema.json": "acp_profile.py",
    "leaven.capability.v1.schema.json": "capability.py",
    "leaven.evaluation_job.v1.schema.json": "evaluation_job.py",
    "leaven.evidence_envelope.v1.schema.json": "evidence_envelope.py",
    "leaven.plan.v1.schema.json": "plan.py",
    "leaven.plan_result.v1.schema.json": "plan_result.py",
    "leaven.stage_payloads.v1.schema.json": "stage_payloads.py",
}

CODEGEN_FLAGS = [
    "--input-file-type=jsonschema",
    "--output-model-type=pydantic_v2.BaseModel",
    "--target-python-version=3.12",
    "--use-standard-collections",
    "--use-union-operator",
    "--use-schema-description",
    "--use-field-description",
    "--use-default",
    "--collapse-root-models",
    "--disable-timestamp",
    "--use-double-quotes",
    "--formatters", "ruff-format",
    "--formatters", "ruff-check",
]


def run(cmd: list[str], **kw) -> None:
    """Run a subprocess command; raise on non-zero exit."""
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd, check=False, **kw)
    if result.returncode != 0:
        raise SystemExit(f"command failed with exit code {result.returncode}")


def main() -> int:
    if not SOURCE_SCHEMA_DIR.is_dir():
        print(f"source schema dir not found: {SOURCE_SCHEMA_DIR}", file=sys.stderr)
        return 1

    # 1. Preprocess (normalize boolean schemas).
    print("== preprocess ==")
    run(["uv", "run", "python", "codegen/preprocess_schemas.py",
         str(SOURCE_SCHEMA_DIR), str(BUILD_DIR)])

    # 2. Codegen each schema -> module.
    print("\n== codegen ==")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for schema_name, module_name in SCHEMA_TO_MODULE.items():
        src = BUILD_DIR / schema_name
        if not src.is_file():
            print(f"  skip: {schema_name} (no preprocessed file)")
            continue
        dst = OUT_DIR / module_name
        run([
            "uv", "run", "datamodel-codegen",
            "--input", str(src),
            "--output", str(dst),
            *CODEGEN_FLAGS,
        ])

    # 3. Write _types/__init__.py if it doesn't have one.
    init = OUT_DIR / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""Code-generated typed records from the locked public-seam-v1 schemas.\n'
            "\n"
            "These modules are regenerated by `just codegen` (see\n"
            "`codegen/generate_types.py`) from\n"
            "`docs/specs/public-seam-v1/schemas/*.schema.json`. Do not edit by hand;\n"
            "manual edits will be overwritten on the next regeneration.\n"
            "\n"
            "This package lives under `_types/` because the codegen output is\n"
            "internal scaffold material — the eventual published `leaven-types`\n"
            "Python package will own these records via the same generation\n"
            "pipeline, with explicit public surface.\n"
            '"""\n'
            "\n"
            "from __future__ import annotations\n"
        )

    # 4. Clean up build dir.
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
        print(f"\ncleaned up {BUILD_DIR.relative_to(ROOT)}")

    print("\n== done ==")
    print(f"output: {OUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
