[package]
name = "leaven-store-file"
description = "Local filesystem backend for Leaven storage capabilities."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
leaven-kernel = { workspace = true }
leaven-store = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
