"""Render generated Plan expression records for public-seam payloads."""

EXPRESSION_EXPORTS = (
    "ExtensionObjectExpression GraphSource GraphSourceAssessmentSet GraphSourceByCandidate "
    "GraphSourceByProposal GraphSourceByProposalBatch GraphSourceCandidateSet "
    "GraphSourceCandidateTree GraphSourceCosts GraphSourceEvents GraphSourceExtension "
    "GraphSourceRecentFailures PageRequest PlanExpression PlanExpressionCaseQuery "
    "PlanExpressionExtract PlanExpressionFilter PlanExpressionGraphQuery PlanExpressionLimit "
    "PlanExpressionLiteral PlanExpressionProject PlanExpressionRefsFromResult "
    "PlanExpressionSort PlanExpressionTemplate PlanExpressionVar PlanExpressionWorkspaceQuery Precondition "
    "PreconditionAssessmentExists PreconditionCandidateExists PreconditionCandidateIdentity "
    "PreconditionGraphRevisionAtLeast PreconditionGraphRevisionEquals PreconditionReceiptExists "
    "PreconditionSchemaValid SortKey"
)


def render_expressions() -> str:
    """Render generated Plan expression records as their own private wire module."""
    return f'''"""Generated public-seam Plan expression records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType, field

from .refs import (
    AssessmentRef,
    CandidateRef,
    ProposalBatchRef,
    ProposalRef,
    ReceiptRef,
    WireJsonField,
    WireJsonObject,
    WorkspaceRef,
)


class PageRequest(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    limit: int | UnsetType = UNSET
    cursor: str | UnsetType = UNSET
    stable_order: bool | UnsetType = UNSET


class SortKey(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    field: str
    direction: Literal["asc", "desc"]
    nulls: Literal["first", "last"] | UnsetType = UNSET


class GraphSourceByCandidate(Struct, frozen=True, forbid_unknown_fields=True, tag="by_candidate", tag_field="kind"):
    candidate: CandidateRef


class GraphSourceCandidateSet(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="candidate_set", tag_field="kind"):
    filter: WireJsonObject | UnsetType = UNSET


class GraphSourceByProposal(Struct, frozen=True, forbid_unknown_fields=True, tag="by_proposal", tag_field="kind"):
    proposal: ProposalRef


class GraphSourceByProposalBatch(Struct, frozen=True, forbid_unknown_fields=True, tag="by_proposal_batch", tag_field="kind"):
    proposal_batch: ProposalBatchRef


class GraphSourceAssessmentSet(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="assessment_set", tag_field="kind"):
    filter: WireJsonObject | UnsetType = UNSET


class GraphSourceRecentFailures(Struct, frozen=True, forbid_unknown_fields=True, tag="recent_failures", tag_field="kind"):
    limit: int


class GraphSourceCosts(Struct, frozen=True, forbid_unknown_fields=True, tag="costs", tag_field="kind"):
    scope: WireJsonField


class GraphSourceEvents(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="events", tag_field="kind"):
    since_revision: str | UnsetType = UNSET
    until_revision: str | UnsetType = UNSET
    filter: WireJsonObject | UnsetType = UNSET


class GraphSourceCandidateTree(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="candidate_tree", tag_field="kind"):
    root: CandidateRef | UnsetType = UNSET
    depth: int | UnsetType = UNSET


class GraphSourceExtension(Struct, frozen=True, forbid_unknown_fields=True, tag="extension", tag_field="kind"):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: WireJsonField


type GraphSource = (
    GraphSourceByCandidate
    | GraphSourceCandidateSet
    | GraphSourceByProposal
    | GraphSourceByProposalBatch
    | GraphSourceAssessmentSet
    | GraphSourceRecentFailures
    | GraphSourceCosts
    | GraphSourceEvents
    | GraphSourceCandidateTree
    | GraphSourceExtension
)


class PlanExpressionLiteral(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="literal", tag_field="kind"):
    value: WireJsonField
    data_classes: list[str] | UnsetType = UNSET


class PlanExpressionVar(Struct, frozen=True, forbid_unknown_fields=True, tag="var", tag_field="kind"):
    name: str


class PlanExpressionGraphQuery(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="graph_query", tag_field="kind"):
    source: GraphSource
    projection: WireJsonObject
    steps: list[WireJsonObject] | UnsetType = UNSET
    page: PageRequest | UnsetType = UNSET


class PlanExpressionCaseQuery(Struct, frozen=True, forbid_unknown_fields=True, tag="case_query", tag_field="kind"):
    query: WireJsonObject


class PlanExpressionWorkspaceQuery(Struct, frozen=True, forbid_unknown_fields=True, tag="workspace_query", tag_field="kind"):
    workspace: WorkspaceRef
    op: WireJsonObject


class PlanExpressionProject(Struct, frozen=True, forbid_unknown_fields=True, tag="project", tag_field="kind"):
    input: WireJsonObject
    projection: WireJsonObject


class PlanExpressionFilter(Struct, frozen=True, forbid_unknown_fields=True, tag="filter", tag_field="kind"):
    input: WireJsonObject
    predicate: WireJsonObject


class PlanExpressionSort(Struct, frozen=True, forbid_unknown_fields=True, tag="sort", tag_field="kind"):
    input: WireJsonObject
    keys: list[SortKey]


class PlanExpressionLimit(Struct, frozen=True, forbid_unknown_fields=True, tag="limit", tag_field="kind"):
    input: WireJsonObject
    limit: int


class PlanExpressionTemplate(Struct, frozen=True, forbid_unknown_fields=True, tag="template", tag_field="kind"):
    dialect: str
    template: str
    vars: dict[str, WireJsonObject]


class PlanExpressionExtract(Struct, frozen=True, forbid_unknown_fields=True, tag="extract", tag_field="kind"):
    input: WireJsonObject
    path: str


class PlanExpressionRefsFromResult(Struct, frozen=True, forbid_unknown_fields=True, tag="refs_from_result", tag_field="kind"):
    from_: str = field(name="from")


class ExtensionObjectExpression(Struct, frozen=True, forbid_unknown_fields=True, tag="extension", tag_field="kind"):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: WireJsonField


type PlanExpression = (
    PlanExpressionLiteral
    | PlanExpressionVar
    | PlanExpressionGraphQuery
    | PlanExpressionCaseQuery
    | PlanExpressionWorkspaceQuery
    | PlanExpressionProject
    | PlanExpressionFilter
    | PlanExpressionSort
    | PlanExpressionLimit
    | PlanExpressionTemplate
    | PlanExpressionExtract
    | PlanExpressionRefsFromResult
    | ExtensionObjectExpression
)


class PreconditionCandidateExists(Struct, frozen=True, forbid_unknown_fields=True, tag="candidate_exists", tag_field="kind"):
    candidate: CandidateRef


class PreconditionCandidateIdentity(Struct, frozen=True, forbid_unknown_fields=True, tag="candidate_identity", tag_field="kind"):
    candidate: CandidateRef
    identity: str


class PreconditionGraphRevisionAtLeast(Struct, frozen=True, forbid_unknown_fields=True, tag="graph_revision_at_least", tag_field="kind"):
    revision: str


class PreconditionGraphRevisionEquals(Struct, frozen=True, forbid_unknown_fields=True, tag="graph_revision_equals", tag_field="kind"):
    revision: str


class PreconditionAssessmentExists(Struct, frozen=True, forbid_unknown_fields=True, tag="assessment_exists", tag_field="kind"):
    assessment: AssessmentRef


class PreconditionReceiptExists(Struct, frozen=True, forbid_unknown_fields=True, tag="receipt_exists", tag_field="kind"):
    receipt: ReceiptRef


class PreconditionSchemaValid(Struct, frozen=True, forbid_unknown_fields=True, tag="schema_valid", tag_field="kind"):
    schema_fingerprint: str
    value: WireJsonObject


type Precondition = (
    PreconditionCandidateExists
    | PreconditionCandidateIdentity
    | PreconditionGraphRevisionAtLeast
    | PreconditionGraphRevisionEquals
    | PreconditionAssessmentExists
    | PreconditionReceiptExists
    | PreconditionSchemaValid
)


__all__ = (  # noqa: PLE0605, SIM905
    "{EXPRESSION_EXPORTS}"
).split()
'''
