"""Render generated Plan expression records for public-seam payloads."""
EXPRESSION_EXPORTS = (
    "ArtifactProjection AssessmentFilter CandidateFilter CaseQuery CaseQueryLoad CaseQueryResolveSet EvaluationSetCases "
    "EvaluationSetDifference EvaluationSetExpr EvaluationSetIntersect EvaluationSetNamed EvaluationSetRecent EvaluationSetSample "
    "EvaluationSetStratified EvaluationSetTagged EvaluationSetUnion ExtensionObjectExpression GraphEdge GraphEdgeAssessments "
    "GraphEdgeChildren GraphEdgeDescendants GraphEdgeInformed GraphEdgeInformedBy GraphEdgeLineage GraphEdgePairwiseAssessments "
    "GraphEdgeParents GraphEdgeProposalThatCreated GraphEdgeSiblings GraphSource GraphSourceAssessmentSet GraphSourceByCandidate "
    "GraphSourceByProposal GraphSourceByProposalBatch GraphSourceCandidateSet GraphSourceCandidateTree GraphSourceCosts "
    "GraphSourceEvents GraphSourceExtension GraphSourceRecentFailures GraphStep GraphStepFilter GraphStepLimit GraphStepProject "
    "GraphStepSort GraphStepTraverse PageRequest PlanExpression PlanExpressionCaseQuery PlanExpressionExtract PlanExpressionFilter "
    "PlanExpressionGraphQuery PlanExpressionLimit PlanExpressionLiteral PlanExpressionProject PlanExpressionRefsFromResult "
    "PlanExpressionSort PlanExpressionTemplate PlanExpressionVar PlanExpressionWorkspaceQuery Precondition "
    "PreconditionAssessmentExists PreconditionCandidateExists PreconditionCandidateIdentity PreconditionGraphRevisionAtLeast "
    "PreconditionGraphRevisionEquals PreconditionReceiptExists PreconditionSchemaValid Predicate PredicateAnd PredicateContains "
    "PredicateEq PredicateExists PredicateGt PredicateGte PredicateIn PredicateIsNull PredicateLt PredicateLte PredicateMatches "
    "PredicateNe PredicateNot PredicateOr Projection ProjectionArtifact ProjectionAssessment ProjectionCandidate ProjectionDiff "
    "PlanLiteralValue ProjectionExtension ProjectionIds ProjectionSummary SortKey ValidationErrorItem ValidationReceipt ValueExpr ValueExprExtension ValueExprExtract ValueExprLiteral ValueExprVar WorkspaceQuery WorkspaceQueryCaptureArtifacts WorkspaceQueryDigest WorkspaceQueryGitDiff WorkspaceQueryGitLog WorkspaceQueryGitStatus WorkspaceQueryList WorkspaceQueryReadFile WorkspaceQuerySnapshot WorkspaceQueryStat"
)

def render_expressions() -> str:
    """Render generated Plan expression records as their own private wire module."""
    return f'''"""Generated public-seam Plan expression records.
Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType, field

from .refs import (
    ArtifactSelector,
    AssessmentRef,
    CandidateRef,
    CaseRef,
    CostScope,
    EvaluationRequestRef,
    ExtensionPayload,
    GraphEventFilterPayload,
    PlanLiteralValue,
    ProposalBatchRef,
    ProposalRef,
    ReceiptRef,
    WorkspaceRef,
)


class PageRequest(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    limit: int | UnsetType = UNSET
    cursor: str | UnsetType = UNSET
    stable_order: bool | UnsetType = UNSET


class SortKey(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    field: str
    direction: Literal["asc", "desc"]
    nulls: Literal["first", "last"] | UnsetType = UNSET


class PredicateEq(Struct, frozen=True, forbid_unknown_fields=True, tag="eq", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateNe(Struct, frozen=True, forbid_unknown_fields=True, tag="ne", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateGt(Struct, frozen=True, forbid_unknown_fields=True, tag="gt", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateGte(Struct, frozen=True, forbid_unknown_fields=True, tag="gte", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateLt(Struct, frozen=True, forbid_unknown_fields=True, tag="lt", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateLte(Struct, frozen=True, forbid_unknown_fields=True, tag="lte", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateContains(Struct, frozen=True, forbid_unknown_fields=True, tag="contains", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateMatches(Struct, frozen=True, forbid_unknown_fields=True, tag="matches", tag_field="kind"):
    field: str
    value: PlanLiteralValue


class PredicateIn(Struct, frozen=True, forbid_unknown_fields=True, tag="in", tag_field="kind"):
    field: str
    values: list[PlanLiteralValue]


class PredicateExists(Struct, frozen=True, forbid_unknown_fields=True, tag="exists", tag_field="kind"):
    field: str


class PredicateIsNull(Struct, frozen=True, forbid_unknown_fields=True, tag="is_null", tag_field="kind"):
    field: str


class PredicateAnd(Struct, frozen=True, forbid_unknown_fields=True, tag="and", tag_field="kind"):
    predicates: list["Predicate"]


class PredicateOr(Struct, frozen=True, forbid_unknown_fields=True, tag="or", tag_field="kind"):
    predicates: list["Predicate"]


class PredicateNot(Struct, frozen=True, forbid_unknown_fields=True, tag="not", tag_field="kind"):
    predicate: "Predicate"


type Predicate = (
    PredicateEq
    | PredicateNe
    | PredicateGt
    | PredicateGte
    | PredicateLt
    | PredicateLte
    | PredicateContains
    | PredicateMatches
    | PredicateIn
    | PredicateExists
    | PredicateIsNull
    | PredicateAnd
    | PredicateOr
    | PredicateNot
)


class ArtifactProjection(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    surface_fingerprint: str
    projection_schema: str
    selector_schema: str | UnsetType = UNSET
    selector: ArtifactSelector | UnsetType = UNSET
    max_bytes: int | UnsetType = UNSET
    data_classes: list[str] | UnsetType = UNSET


class ProjectionIds(Struct, frozen=True, forbid_unknown_fields=True, tag="ids", tag_field="kind"):
    pass


class ProjectionSummary(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="summary", tag_field="kind"):
    fields: list[str] | UnsetType = UNSET


class ProjectionCandidate(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="candidate_projection", tag_field="kind"):
    fields: list[str] | UnsetType = UNSET
    artifact: ArtifactProjection | UnsetType = UNSET


class ProjectionArtifact(Struct, frozen=True, forbid_unknown_fields=True, tag="artifact_projection", tag_field="kind"):
    artifact: ArtifactProjection


class ProjectionAssessment(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="assessment_projection", tag_field="kind"):
    fields: list[str] | UnsetType = UNSET
    evidence_visibility: Literal["public", "optimizer_visible", "host_private"] | UnsetType = UNSET


class ProjectionDiff(Struct, frozen=True, forbid_unknown_fields=True, tag="diff_projection", tag_field="kind"):
    surface_fingerprint: str
    diff_schema: str
    left: CandidateRef
    right: CandidateRef


class ProjectionExtension(Struct, frozen=True, forbid_unknown_fields=True, tag="extension", tag_field="kind"):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: ExtensionPayload


type Projection = (
    ProjectionIds
    | ProjectionSummary
    | ProjectionCandidate
    | ProjectionArtifact
    | ProjectionAssessment
    | ProjectionDiff
    | ProjectionExtension
)


class CandidateFilter(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    ids: list[CandidateRef] | UnsetType = UNSET
    predicate: Predicate | UnsetType = UNSET


class AssessmentFilter(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    candidate: CandidateRef | UnsetType = UNSET
    case: CaseRef | UnsetType = UNSET
    request: EvaluationRequestRef | UnsetType = UNSET
    kind: Literal["independent", "pairwise", "listwise"] | UnsetType = UNSET
    predicate: Predicate | UnsetType = UNSET


class GraphEdgeParents(Struct, frozen=True, forbid_unknown_fields=True, tag="parents", tag_field="kind"):
    pass


class GraphEdgeChildren(Struct, frozen=True, forbid_unknown_fields=True, tag="children", tag_field="kind"):
    pass


class GraphEdgeSiblings(Struct, frozen=True, forbid_unknown_fields=True, tag="siblings", tag_field="kind"):
    pass


class GraphEdgeInformedBy(Struct, frozen=True, forbid_unknown_fields=True, tag="informed_by", tag_field="kind"):
    pass


class GraphEdgeInformed(Struct, frozen=True, forbid_unknown_fields=True, tag="informed", tag_field="kind"):
    pass


class GraphEdgeProposalThatCreated(Struct, frozen=True, forbid_unknown_fields=True, tag="proposal_that_created", tag_field="kind"):
    pass


class GraphEdgeLineage(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="lineage", tag_field="kind"):
    depth: int | UnsetType = UNSET


class GraphEdgeDescendants(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="descendants", tag_field="kind"):
    depth: int | UnsetType = UNSET


class GraphEdgeAssessments(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="assessments", tag_field="kind"):
    filter: AssessmentFilter | UnsetType = UNSET


class GraphEdgePairwiseAssessments(Struct, frozen=True, forbid_unknown_fields=True, tag="pairwise_assessments", tag_field="kind"):
    other: CandidateRef


type GraphEdge = (
    GraphEdgeParents
    | GraphEdgeChildren
    | GraphEdgeSiblings
    | GraphEdgeInformedBy
    | GraphEdgeInformed
    | GraphEdgeProposalThatCreated
    | GraphEdgeLineage
    | GraphEdgeDescendants
    | GraphEdgeAssessments
    | GraphEdgePairwiseAssessments
)


class GraphStepTraverse(Struct, frozen=True, forbid_unknown_fields=True, tag="traverse", tag_field="kind"):
    edge: GraphEdge


class GraphStepFilter(Struct, frozen=True, forbid_unknown_fields=True, tag="filter", tag_field="kind"):
    predicate: Predicate


class GraphStepSort(Struct, frozen=True, forbid_unknown_fields=True, tag="sort", tag_field="kind"):
    keys: list[SortKey]


class GraphStepLimit(Struct, frozen=True, forbid_unknown_fields=True, tag="limit", tag_field="kind"):
    limit: int


class GraphStepProject(Struct, frozen=True, forbid_unknown_fields=True, tag="project", tag_field="kind"):
    projection: Projection


type GraphStep = GraphStepTraverse | GraphStepFilter | GraphStepSort | GraphStepLimit | GraphStepProject


class GraphSourceByCandidate(Struct, frozen=True, forbid_unknown_fields=True, tag="by_candidate", tag_field="kind"):
    candidate: CandidateRef


class GraphSourceCandidateSet(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="candidate_set", tag_field="kind"):
    filter: CandidateFilter | UnsetType = UNSET


class GraphSourceByProposal(Struct, frozen=True, forbid_unknown_fields=True, tag="by_proposal", tag_field="kind"):
    proposal: ProposalRef


class GraphSourceByProposalBatch(Struct, frozen=True, forbid_unknown_fields=True, tag="by_proposal_batch", tag_field="kind"):
    proposal_batch: ProposalBatchRef


class GraphSourceAssessmentSet(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="assessment_set", tag_field="kind"):
    filter: AssessmentFilter | UnsetType = UNSET


class GraphSourceRecentFailures(Struct, frozen=True, forbid_unknown_fields=True, tag="recent_failures", tag_field="kind"):
    limit: int


class GraphSourceCosts(Struct, frozen=True, forbid_unknown_fields=True, tag="costs", tag_field="kind"):
    scope: CostScope


class GraphSourceEvents(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="events", tag_field="kind"):
    since_revision: str | UnsetType = UNSET
    until_revision: str | UnsetType = UNSET
    filter: GraphEventFilterPayload | UnsetType = UNSET


class GraphSourceCandidateTree(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="candidate_tree", tag_field="kind"):
    root: CandidateRef | UnsetType = UNSET
    depth: int | UnsetType = UNSET


class GraphSourceExtension(Struct, frozen=True, forbid_unknown_fields=True, tag="extension", tag_field="kind"):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: ExtensionPayload


type GraphSource = (
    GraphSourceByCandidate
    | GraphSourceCandidateSet
    | GraphSourceByProposal
    | GraphSourceByProposalBatch
    | GraphSourceAssessmentSet
    | GraphSourceRecentFailures
    | GraphSourceCosts
    | GraphSourceEvents
    | GraphSourceCandidateTree
    | GraphSourceExtension
)


class PlanExpressionLiteral(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="literal", tag_field="kind"):
    value: PlanLiteralValue
    data_classes: list[str] | UnsetType = UNSET


class PlanExpressionVar(Struct, frozen=True, forbid_unknown_fields=True, tag="var", tag_field="kind"):
    name: str


class PlanExpressionGraphQuery(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="graph_query", tag_field="kind"):
    source: GraphSource
    projection: Projection
    steps: list[GraphStep] | UnsetType = UNSET
    page: PageRequest | UnsetType = UNSET


class PlanExpressionCaseQuery(Struct, frozen=True, forbid_unknown_fields=True, tag="case_query", tag_field="kind"):
    query: "CaseQuery"


class EvaluationSetNamed(Struct, frozen=True, forbid_unknown_fields=True, tag="named", tag_field="kind"):
    name: str


class EvaluationSetCases(Struct, frozen=True, forbid_unknown_fields=True, tag="cases", tag_field="kind"):
    cases: list[CaseRef]
    requires_partition_resolution: bool

    def __post_init__(self) -> None:
        if self.requires_partition_resolution is not True:
            raise ValueError("requires_partition_resolution must be true")


class EvaluationSetTagged(Struct, frozen=True, forbid_unknown_fields=True, tag="tagged", tag_field="kind"):
    tag: str
    requires_partition_resolution: bool

    def __post_init__(self) -> None:
        if self.requires_partition_resolution is not True:
            raise ValueError("requires_partition_resolution must be true")


class EvaluationSetRecent(Struct, frozen=True, forbid_unknown_fields=True, tag="recent", tag_field="kind"):
    limit: int
    requires_partition_resolution: bool

    def __post_init__(self) -> None:
        if self.requires_partition_resolution is not True:
            raise ValueError("requires_partition_resolution must be true")


class EvaluationSetUnion(Struct, frozen=True, forbid_unknown_fields=True, tag="union", tag_field="kind"):
    sets: list["EvaluationSetExpr"]


class EvaluationSetIntersect(Struct, frozen=True, forbid_unknown_fields=True, tag="intersect", tag_field="kind"):
    sets: list["EvaluationSetExpr"]


class EvaluationSetDifference(Struct, frozen=True, forbid_unknown_fields=True, tag="difference", tag_field="kind"):
    base: "EvaluationSetExpr"
    subtract: "EvaluationSetExpr"


class EvaluationSetSample(Struct, frozen=True, forbid_unknown_fields=True, tag="sample", tag_field="kind"):
    base: "EvaluationSetExpr"
    n: int
    seed: int


class EvaluationSetStratified(Struct, frozen=True, forbid_unknown_fields=True, tag="stratified", tag_field="kind"):
    base: "EvaluationSetExpr"
    by: str
    per_bucket: int
    seed: int


type EvaluationSetExpr = (
    EvaluationSetNamed
    | EvaluationSetCases
    | EvaluationSetTagged
    | EvaluationSetRecent
    | EvaluationSetUnion
    | EvaluationSetIntersect
    | EvaluationSetDifference
    | EvaluationSetSample
    | EvaluationSetStratified
)


class CaseQueryResolveSet(Struct, frozen=True, forbid_unknown_fields=True, tag="resolve_set", tag_field="kind"):
    set: EvaluationSetExpr
    purpose: Literal["train", "validation", "test", "diagnostic", "custom"]


class CaseQueryLoad(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="load", tag_field="kind"):
    case: CaseRef
    include: list[Literal["input", "target", "metadata"]]
    projection_schema: str | UnsetType = UNSET


type CaseQuery = CaseQueryResolveSet | CaseQueryLoad


class WorkspaceQuerySnapshot(Struct, frozen=True, forbid_unknown_fields=True, tag="snapshot", tag_field="kind"):
    pass


class WorkspaceQueryList(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="list", tag_field="kind"):
    path: str
    recursive: bool | UnsetType = UNSET
    max_entries: int | UnsetType = UNSET


class WorkspaceQueryReadFile(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="read_file", tag_field="kind"):
    path: str
    expected_data_classes: list[str]
    max_bytes: int | UnsetType = UNSET


class WorkspaceQueryStat(Struct, frozen=True, forbid_unknown_fields=True, tag="stat", tag_field="kind"):
    path: str


class WorkspaceQueryDigest(Struct, frozen=True, forbid_unknown_fields=True, tag="digest", tag_field="kind"):
    path: str
    algorithm: Literal["sha256", "blake3"]


class WorkspaceQueryGitLog(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="git_log", tag_field="kind"):
    max_entries: int | UnsetType = UNSET


class WorkspaceQueryGitDiff(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="git_diff", tag_field="kind"):
    against: Literal["seed", "parent", "baseline", "head"]
    max_bytes: int | UnsetType = UNSET


class WorkspaceQueryGitStatus(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="git_status", tag_field="kind"):
    porcelain: bool | UnsetType = UNSET


class WorkspaceQueryCaptureArtifacts(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="capture_artifacts", tag_field="kind"):
    paths: list[str]
    max_bytes: int | UnsetType = UNSET


type WorkspaceQuery = (
    WorkspaceQuerySnapshot
    | WorkspaceQueryList
    | WorkspaceQueryReadFile
    | WorkspaceQueryStat
    | WorkspaceQueryDigest
    | WorkspaceQueryGitLog
    | WorkspaceQueryGitDiff
    | WorkspaceQueryGitStatus
    | WorkspaceQueryCaptureArtifacts
)


class PlanExpressionWorkspaceQuery(Struct, frozen=True, forbid_unknown_fields=True, tag="workspace_query", tag_field="kind"):
    workspace: WorkspaceRef
    op: WorkspaceQuery


class PlanExpressionProject(Struct, frozen=True, forbid_unknown_fields=True, tag="project", tag_field="kind"):
    input: "PlanExpression"
    projection: Projection


class PlanExpressionFilter(Struct, frozen=True, forbid_unknown_fields=True, tag="filter", tag_field="kind"):
    input: "PlanExpression"
    predicate: Predicate


class PlanExpressionSort(Struct, frozen=True, forbid_unknown_fields=True, tag="sort", tag_field="kind"):
    input: "PlanExpression"
    keys: list[SortKey]


class PlanExpressionLimit(Struct, frozen=True, forbid_unknown_fields=True, tag="limit", tag_field="kind"):
    input: "PlanExpression"
    limit: int


class PlanExpressionTemplate(Struct, frozen=True, forbid_unknown_fields=True, tag="template", tag_field="kind"):
    dialect: str
    template: str
    vars: dict[str, "PlanExpression"]


class PlanExpressionExtract(Struct, frozen=True, forbid_unknown_fields=True, tag="extract", tag_field="kind"):
    input: "PlanExpression"
    path: str


class PlanExpressionRefsFromResult(Struct, frozen=True, forbid_unknown_fields=True, tag="refs_from_result", tag_field="kind"):
    from_: str = field(name="from")


class ExtensionObjectExpression(Struct, frozen=True, forbid_unknown_fields=True, tag="extension", tag_field="kind"):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: ExtensionPayload


type PlanExpression = (
    PlanExpressionLiteral
    | PlanExpressionVar
    | PlanExpressionGraphQuery
    | PlanExpressionCaseQuery
    | PlanExpressionWorkspaceQuery
    | PlanExpressionProject
    | PlanExpressionFilter
    | PlanExpressionSort
    | PlanExpressionLimit
    | PlanExpressionTemplate
    | PlanExpressionExtract
    | PlanExpressionRefsFromResult
    | ExtensionObjectExpression
)


class ValueExprLiteral(Struct, frozen=True, forbid_unknown_fields=True, tag="literal", tag_field="kind"):
    value: PlanLiteralValue


class ValueExprVar(Struct, frozen=True, forbid_unknown_fields=True, tag="var", tag_field="kind"):
    name: str


class ValueExprExtract(Struct, frozen=True, forbid_unknown_fields=True, tag="extract", tag_field="kind"):
    input: "ValueExpr"
    path: str


class ValueExprExtension(Struct, frozen=True, forbid_unknown_fields=True, tag="extension", tag_field="kind"):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: ExtensionPayload


type ValueExpr = ValueExprLiteral | ValueExprVar | ValueExprExtract | ValueExprExtension


class PreconditionCandidateExists(Struct, frozen=True, forbid_unknown_fields=True, tag="candidate_exists", tag_field="kind"):
    candidate: CandidateRef


class PreconditionCandidateIdentity(Struct, frozen=True, forbid_unknown_fields=True, tag="candidate_identity", tag_field="kind"):
    candidate: CandidateRef
    identity: str


class PreconditionGraphRevisionAtLeast(Struct, frozen=True, forbid_unknown_fields=True, tag="graph_revision_at_least", tag_field="kind"):
    revision: str


class PreconditionGraphRevisionEquals(Struct, frozen=True, forbid_unknown_fields=True, tag="graph_revision_equals", tag_field="kind"):
    revision: str


class PreconditionAssessmentExists(Struct, frozen=True, forbid_unknown_fields=True, tag="assessment_exists", tag_field="kind"):
    assessment: AssessmentRef


class PreconditionReceiptExists(Struct, frozen=True, forbid_unknown_fields=True, tag="receipt_exists", tag_field="kind"):
    receipt: ReceiptRef


class PreconditionSchemaValid(Struct, frozen=True, forbid_unknown_fields=True, tag="schema_valid", tag_field="kind"):
    schema_fingerprint: str
    value: ValueExpr


type Precondition = (
    PreconditionCandidateExists
    | PreconditionCandidateIdentity
    | PreconditionGraphRevisionAtLeast
    | PreconditionGraphRevisionEquals
    | PreconditionAssessmentExists
    | PreconditionReceiptExists
    | PreconditionSchemaValid
)


class ValidationErrorItem(Struct, frozen=True, forbid_unknown_fields=True):
    path: str
    message: str


class ValidationReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    receipt: ReceiptRef
    status: Literal["passed", "failed"]
    schema_fingerprint: str | UnsetType = UNSET
    errors: list[ValidationErrorItem] | UnsetType = UNSET

__all__ = (  # noqa: PLE0605, SIM905
    "{EXPRESSION_EXPORTS}"
).split()
'''
