"""Generate private Python seam wire metadata from a Rust public-seam export."""

import argparse
import json
import subprocess
from pathlib import Path
from typing import TypedDict

REPO_ROOT = Path(__file__).resolve().parents[3]
WIRE_DIR = REPO_ROOT / "sdk/python/src/leaven/_seam/_wire"
METHODS_OUTPUT = WIRE_DIR / "methods.py"
PAYLOADS_OUTPUT = WIRE_DIR / "payloads.py"


class MethodRow(TypedDict):
    """One exported locked public-seam method row."""

    method: str
    params_schema: str
    result_schema: str
    required_action: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str
    produces_receipt: bool


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated output differs")
    args = parser.parse_args()

    generated = generated_files()
    if args.check:
        stale = [path for path, content in generated.items() if path.read_text() != content]
        if stale:
            raise SystemExit(f"generated seam wire files are stale: {stale!r}")
        return
    for path, content in generated.items():
        path.write_text(content, encoding="utf-8")


def generated_files() -> dict[Path, str]:
    rows = export_profile_rows()
    return {
        METHODS_OUTPUT: render_methods(rows),
        PAYLOADS_OUTPUT: render_payloads(rows),
    }


def export_profile_rows() -> list[MethodRow]:
    output = subprocess.check_output(
        [
            "cargo",
            "run",
            "-q",
            "-p",
            "leaven-cli",
            "--",
            "seam",
            "profile",
            "--root",
            str(REPO_ROOT),
        ],
        cwd=REPO_ROOT,
        text=True,
    )
    document = json.loads(output)
    if document["schema_version"] != "leaven.seam_profile_export.v1":
        raise ValueError("unexpected seam profile export schema_version")
    return [
        {
            "method": row["method"],
            "params_schema": row["params_schema"],
            "result_schema": row["result_schema"],
            "required_action": row["required_action"],
            "params_schema_fingerprint": row["params_schema_fingerprint"],
            "result_schema_fingerprint": row["result_schema_fingerprint"],
            "produces_receipt": row["produces_receipt"],
        }
        for row in document["extension_methods"]
    ]


def render_methods(rows: list[MethodRow]) -> str:
    method_literals = "\n    | ".join(f'Literal["{row["method"]}"]' for row in rows)
    method_tuple = "\n".join(f'    "{row["method"]}",' for row in rows)
    binding_rows = "\n".join(
        "    LockedMethodBinding(\n"
        f'        method="{row["method"]}",\n'
        f'        params_schema="{row["params_schema"]}",\n'
        f'        result_schema="{row["result_schema"]}",\n'
        f'        required_action="{row["required_action"]}",\n'
        f'        params_schema_fingerprint="{row["params_schema_fingerprint"]}",\n'
        f'        result_schema_fingerprint="{row["result_schema_fingerprint"]}",\n'
        f"        produces_receipt={row['produces_receipt']},\n"
        "    ),"
        for row in rows
    )
    return f'''"""Generated locked public-seam V1 method metadata.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal, cast

from msgspec import Struct

type LockedMethod = (
    {method_literals}
)


class LockedMethodBinding(Struct, frozen=True):
    """A generated public-seam method/profile binding."""

    method: LockedMethod
    params_schema: str
    result_schema: str
    required_action: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str
    produces_receipt: bool


LOCKED_METHODS: tuple[LockedMethod, ...] = (
{method_tuple}
)

METHOD_BINDINGS: tuple[LockedMethodBinding, ...] = (
{binding_rows}
)

_METHOD_BINDING_BY_NAME: dict[str, LockedMethodBinding] = {{
    binding.method: binding for binding in METHOD_BINDINGS
}}


def require_locked_method(method: str) -> LockedMethod:
    """Return `method` as a locked V1 method or raise `ValueError`."""
    if method not in _METHOD_BINDING_BY_NAME:
        raise ValueError(f"unknown locked Leaven public-seam method: {{method}}")
    return cast("LockedMethod", method)


__all__ = [
    "LOCKED_METHODS",
    "METHOD_BINDINGS",
    "LockedMethod",
    "LockedMethodBinding",
    "require_locked_method",
]
'''


def render_payloads(rows: list[MethodRow]) -> str:
    fingerprints = {row["params_schema"]: row["params_schema_fingerprint"] for row in rows}
    fingerprints.update({row["result_schema"]: row["result_schema_fingerprint"] for row in rows})
    return f'''"""Generated top-level public-seam payload records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Raw, Struct, UnsetType, field

PLAN_SCHEMA_FINGERPRINT = (
    "{fingerprints["leaven.plan.v1.schema.json"]}"
)
PLAN_RESULT_SCHEMA_FINGERPRINT = (
    "{fingerprints["leaven.plan_result.v1.schema.json"]}"
)
STAGE_RUN_SCHEMA_FINGERPRINT = (
    "{fingerprints["leaven.stage_run.v1.schema.json"]}"
)


class PlanDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.plan.v1` payload with nested operation bodies kept raw."""

    schema_version: Literal["leaven.plan.v1"]
    plan_id: str
    consistency: Raw
    mode: Raw
    ops: Raw
    return_: Raw = field(name="return")
    commit: Raw
    metadata: Raw | UnsetType = UNSET


class PlanResultDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.plan_result.v1` result with nested values kept raw."""

    schema_version: Literal["leaven.plan_result.v1"]
    plan_id: str
    capability_fingerprint: str
    policy_fingerprint: str
    base_revision: str
    final_revision: str
    replayability_summary: Raw
    values: Raw
    receipts: Raw
    redactions: Raw
    charges: Raw
    errors: Raw
    metadata: Raw | UnsetType = UNSET


type StageRunKind = Literal["runner"] | Literal["proposer"]


class StageRunRequest(Struct, frozen=True, forbid_unknown_fields=True):
    """Top-level `leaven.stage_run.v1` request with role payload kept raw."""

    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_request"]
    stage: StageRunKind
    payload: Raw


class StageRunResult(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.stage_run.v1` result with output and receipts kept raw."""

    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_result"]
    stage: StageRunKind
    stage_call_id: str
    output: Raw
    effect_receipts: Raw | UnsetType = UNSET
    proposal_receipts: Raw | UnsetType = UNSET


__all__ = [
    "PLAN_RESULT_SCHEMA_FINGERPRINT",
    "PLAN_SCHEMA_FINGERPRINT",
    "STAGE_RUN_SCHEMA_FINGERPRINT",
    "PlanDocument",
    "PlanResultDocument",
    "StageRunKind",
    "StageRunRequest",
    "StageRunResult",
]
'''


if __name__ == "__main__":
    main()
