"""Generate private Python seam wire metadata from a Rust public-seam export."""

import argparse
import json
import subprocess
from pathlib import Path
from typing import TypedDict

REPO_ROOT = Path(__file__).resolve().parents[3]
OUTPUT = REPO_ROOT / "sdk/python/src/leaven/_seam/_wire/methods.py"


class MethodRow(TypedDict):
    """One exported locked public-seam method row."""

    method: str
    params_schema: str
    result_schema: str
    required_action: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str
    produces_receipt: bool


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated output differs")
    args = parser.parse_args()

    generated = render_methods_py()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            raise SystemExit(f"{OUTPUT} is stale; run this generator")
        return
    OUTPUT.write_text(generated, encoding="utf-8")


def render_methods_py() -> str:
    return render(export_profile_rows())


def export_profile_rows() -> list[MethodRow]:
    output = subprocess.check_output(
        [
            "cargo",
            "run",
            "-q",
            "-p",
            "leaven-cli",
            "--",
            "seam",
            "profile",
            "--root",
            str(REPO_ROOT),
        ],
        cwd=REPO_ROOT,
        text=True,
    )
    document = json.loads(output)
    if document["schema_version"] != "leaven.seam_profile_export.v1":
        raise ValueError("unexpected seam profile export schema_version")
    return [
        {
            "method": row["method"],
            "params_schema": row["params_schema"],
            "result_schema": row["result_schema"],
            "required_action": row["required_action"],
            "params_schema_fingerprint": row["params_schema_fingerprint"],
            "result_schema_fingerprint": row["result_schema_fingerprint"],
            "produces_receipt": row["produces_receipt"],
        }
        for row in document["extension_methods"]
    ]


def render(rows: list[MethodRow]) -> str:
    method_literals = "\n    | ".join(f'Literal["{row["method"]}"]' for row in rows)
    method_tuple = "\n".join(f'    "{row["method"]}",' for row in rows)
    binding_rows = "\n".join(
        "    LockedMethodBinding(\n"
        f'        method="{row["method"]}",\n'
        f'        params_schema="{row["params_schema"]}",\n'
        f'        result_schema="{row["result_schema"]}",\n'
        f'        required_action="{row["required_action"]}",\n'
        f'        params_schema_fingerprint="{row["params_schema_fingerprint"]}",\n'
        f'        result_schema_fingerprint="{row["result_schema_fingerprint"]}",\n'
        f"        produces_receipt={row['produces_receipt']},\n"
        "    ),"
        for row in rows
    )
    return f'''"""Generated locked public-seam V1 method metadata.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal, cast

from msgspec import Struct

type LockedMethod = (
    {method_literals}
)


class LockedMethodBinding(Struct, frozen=True):
    """A generated public-seam method/profile binding."""

    method: LockedMethod
    params_schema: str
    result_schema: str
    required_action: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str
    produces_receipt: bool


LOCKED_METHODS: tuple[LockedMethod, ...] = (
{method_tuple}
)

METHOD_BINDINGS: tuple[LockedMethodBinding, ...] = (
{binding_rows}
)

_METHOD_BINDING_BY_NAME: dict[str, LockedMethodBinding] = {{
    binding.method: binding for binding in METHOD_BINDINGS
}}


def require_locked_method(method: str) -> LockedMethod:
    """Return `method` as a locked V1 method or raise `ValueError`."""
    if method not in _METHOD_BINDING_BY_NAME:
        raise ValueError(f"unknown locked Leaven public-seam method: {{method}}")
    return cast("LockedMethod", method)


__all__ = [
    "LOCKED_METHODS",
    "METHOD_BINDINGS",
    "LockedMethod",
    "LockedMethodBinding",
    "require_locked_method",
]
'''


if __name__ == "__main__":
    main()
