"""Render generated locked public-seam method metadata."""

from collections.abc import Sequence
from typing import TypedDict


class MethodCodegenRow(TypedDict):
    """Rust-exported method/profile facts consumed by the method renderer."""

    method: str
    params_schema: str
    result_schema: str
    required_action: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str
    produces_receipt: bool


def render_methods(rows: Sequence[MethodCodegenRow]) -> str:
    method_literals = "\n    | ".join(f'Literal["{row["method"]}"]' for row in rows)
    method_tuple = "\n".join(f'    "{row["method"]}",' for row in rows)
    binding_rows = "\n".join(_binding_row(row) for row in rows)
    return f'''"""Generated locked public-seam V1 method metadata.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal, cast

from msgspec import Struct

type LockedMethod = (
    {method_literals}
)


class LockedMethodBinding(Struct, frozen=True):
    """A generated public-seam method/profile binding."""

    method: LockedMethod
    params_schema: str
    result_schema: str
    required_action: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str
    produces_receipt: bool


LOCKED_METHODS: tuple[LockedMethod, ...] = (
{method_tuple}
)

METHOD_BINDINGS: tuple[LockedMethodBinding, ...] = (
{binding_rows}
)

_METHOD_BINDING_BY_NAME: dict[str, LockedMethodBinding] = {{
    binding.method: binding for binding in METHOD_BINDINGS
}}


def require_locked_method(method: str) -> LockedMethod:
    """Return `method` as a locked V1 method or raise `ValueError`."""
    if method not in _METHOD_BINDING_BY_NAME:
        raise ValueError(f"unknown locked Leaven public-seam method: {{method}}")
    return cast("LockedMethod", method)


__all__ = [
    "LOCKED_METHODS",
    "METHOD_BINDINGS",
    "LockedMethod",
    "LockedMethodBinding",
    "require_locked_method",
]
'''


def _binding_row(row: MethodCodegenRow) -> str:
    return (
        "    LockedMethodBinding(\n"
        f'        method="{row["method"]}",\n'
        f'        params_schema="{row["params_schema"]}",\n'
        f'        result_schema="{row["result_schema"]}",\n'
        f'        required_action="{row["required_action"]}",\n'
        f'        params_schema_fingerprint="{row["params_schema_fingerprint"]}",\n'
        f'        result_schema_fingerprint="{row["result_schema_fingerprint"]}",\n'
        f"        produces_receipt={row['produces_receipt']},\n"
        "    ),"
    )
