"""Render generated msgspec payload records for the private seam wire layer."""

from collections.abc import Sequence
from typing import TypedDict

from ref_codegen import REF_EXPORTS, REF_RECORDS


class PayloadMethodRow(TypedDict):
    """One exported locked public-seam method row used for payload rendering."""

    params_schema: str
    result_schema: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str


def render_payloads(rows: Sequence[PayloadMethodRow]) -> str:
    fingerprints = {row["params_schema"]: row["params_schema_fingerprint"] for row in rows}
    fingerprints.update({row["result_schema"]: row["result_schema_fingerprint"] for row in rows})
    return f'''"""Generated top-level public-seam payload records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType, field

PLAN_SCHEMA_FINGERPRINT = (
    "{fingerprints["leaven.plan.v1.schema.json"]}"
)
PLAN_RESULT_SCHEMA_FINGERPRINT = (
    "{fingerprints["leaven.plan_result.v1.schema.json"]}"
)
STAGE_RUN_SCHEMA_FINGERPRINT = (
    "{fingerprints["leaven.stage_run.v1.schema.json"]}"
)


type WireJsonScalar = str | int | float | bool | None
type WireJsonLeafArray = list[WireJsonScalar]
type WireJsonLeafObject = dict[str, WireJsonScalar | WireJsonLeafArray]
type WireJsonField = WireJsonScalar | WireJsonLeafArray | WireJsonLeafObject
type WireJsonObject = dict[str, WireJsonField]

{REF_RECORDS}

type Replayability = Literal[
    "pure_read",
    "fully_managed",
    "boundary_managed",
    "has_declared_external_effects",
    "has_untracked_external_effects",
]


class ConsistencyLatestAtStart(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="latest_at_start",
    tag_field="kind",
):
    pass


class ConsistencyAtRevision(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="at_revision",
    tag_field="kind",
):
    revision: str


class ConsistencySinceRevision(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="since_revision",
    tag_field="kind",
):
    since: str
    until: str | UnsetType = UNSET


type Consistency = ConsistencyLatestAtStart | ConsistencyAtRevision | ConsistencySinceRevision


class EvalModeExecute(Struct, frozen=True, forbid_unknown_fields=True, tag="execute", tag_field="kind"):
    pass


class EvalModeDryRun(Struct, frozen=True, forbid_unknown_fields=True, tag="dry_run", tag_field="kind"):
    pass


class EvalModeRequireCached(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="require_cached",
    tag_field="kind",
):
    pass


class EvalModeReplay(Struct, frozen=True, forbid_unknown_fields=True, tag="replay", tag_field="kind"):
    receipts: list[ReceiptRef]


type EvalMode = EvalModeExecute | EvalModeDryRun | EvalModeRequireCached | EvalModeReplay


class CommitPolicyNoGraphWrites(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="no_graph_writes",
    tag_field="kind",
):
    pass


type StaleWritePolicy = Literal["reject", "allow_if_policy_allows", "rebase_extension"]


class CommitPolicyGraphWritesAtomic(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="graph_writes_atomic",
    tag_field="kind",
):
    on_stale: StaleWritePolicy


class CommitPolicyGraphWritesSequential(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="graph_writes_sequential",
    tag_field="kind",
):
    on_failure: Literal["stop", "continue"]
    on_stale: StaleWritePolicy


type CommitPolicy = (
    CommitPolicyNoGraphWrites | CommitPolicyGraphWritesAtomic | CommitPolicyGraphWritesSequential
)
type PlanDeps = list[str]
type PlanOpKind = Literal["let", "call", "write"]
type PlanCallKind = Literal[
    "lm_complete", "agent_run", "sandbox_exec", "workspace_materialize", "workspace_release"
]
type PlanWriteKind = Literal[
    "submit_proposal_batch",
    "submit_assessments",
    "request_evaluation",
    "apply_proposal_batch",
    "emit_run_event",
]


class CapabilityCall(Struct, frozen=True, omit_defaults=True, kw_only=True):
    kind: PlanCallKind


class GraphWrite(Struct, frozen=True, omit_defaults=True, kw_only=True):
    kind: PlanWriteKind


class PlanOp(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, kw_only=True):
    kind: PlanOpKind
    name: str
    expr: WireJsonObject | UnsetType = UNSET
    call: CapabilityCall | UnsetType = UNSET
    write: GraphWrite | UnsetType = UNSET
    idempotency_key: str | UnsetType = UNSET
    preconditions: list[WireJsonObject] | UnsetType = UNSET
    deps: PlanDeps | UnsetType = UNSET


class Cost(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    usd_micro: int | UnsetType = UNSET
    input_tokens: int | UnsetType = UNSET
    output_tokens: int | UnsetType = UNSET
    lm_calls: int | UnsetType = UNSET
    agent_calls: int | UnsetType = UNSET
    sandbox_calls: int | UnsetType = UNSET
    metric_calls: int | UnsetType = UNSET
    wall_ms: int | UnsetType = UNSET


class BlobRef(Struct, frozen=True, forbid_unknown_fields=True, tag="blob_ref", tag_field="kind"):
    id: str
    sha256: str
    bytes: int
    data_classes: DataClassSet
    media_type: str | UnsetType = UNSET
    uri: str | UnsetType = UNSET


type VisibilityClass = Literal[
    "public",
    "optimizer_visible",
    "reflector_visible",
    "evaluator_only",
    "operator_only",
    "private",
    "redacted",
]


class OutputRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    kind: Literal["text", "json", "blob_ref", "structured", "agent_session", "workspace_diff"]
    visibility: VisibilityClass
    data_classes: DataClassSet
    summary: str | UnsetType = UNSET
    value: WireJsonField | UnsetType = UNSET
    blob_ref: BlobRef | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET


class Score(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    value: float
    output: OutputRecord
    metrics: dict[str, float] | UnsetType = UNSET
    uncertainty: float | UnsetType = UNSET
    metadata: MetadataBag | UnsetType = UNSET


class CandidateSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="candidate_summary",
    tag_field="kind",
):
    candidate: CandidateRef
    artifact_identity: str | UnsetType = UNSET
    scores: WireJsonField | UnsetType = UNSET
    artifact: WireJsonField | UnsetType = UNSET


class ProposalSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="proposal_summary",
    tag_field="kind",
):
    proposal: ProposalRef
    batch: ProposalBatchRef | UnsetType = UNSET
    effect: WireJsonField | UnsetType = UNSET


class AssessmentSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="assessment_summary",
    tag_field="kind",
):
    assessment: AssessmentRef
    score: Score | UnsetType = UNSET
    evidence: WireJsonField | UnsetType = UNSET


class EventSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="event_summary",
    tag_field="kind",
):
    event_kind: str
    revision: str
    payload: WireJsonField | UnsetType = UNSET


class ExtensionGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="extension",
    tag_field="kind",
):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: WireJsonField


type GraphRow = (
    CandidateSummaryGraphRow
    | ProposalSummaryGraphRow
    | AssessmentSummaryGraphRow
    | EventSummaryGraphRow
    | ExtensionGraphRow
)


class Redaction(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    path: str
    reason: str
    policy_fingerprint: str | UnsetType = UNSET
    public_reason: str | UnsetType = UNSET
    audit_reason: str | UnsetType = UNSET


class PlanError(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    code: str
    message: str
    op: str | UnsetType = UNSET
    path: str | UnsetType = UNSET
    receipt: ReceiptRef | UnsetType = UNSET
    retryable: bool | UnsetType = UNSET
    details: WireJsonField | UnsetType = UNSET


class StageCost(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    usd_micro: int | UnsetType = UNSET
    input_tokens: int | UnsetType = UNSET
    output_tokens: int | UnsetType = UNSET
    lm_calls: int | UnsetType = UNSET


class StageEffectReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    method: Literal["leaven/lm.complete", "leaven/agent.run"]
    receipt: str
    call_kind: Literal["lm_complete", "agent_run"] | UnsetType = UNSET
    cost: StageCost | UnsetType = UNSET
    blob_refs: list[BlobRef] | UnsetType = UNSET


class StageProposalReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    method: Literal["leaven/proposal.submit_batch"]
    receipt: ReceiptRef
    write_kind: Literal["submit_proposal_batch"] | UnsetType = UNSET
    proposal_ids: list[str] | UnsetType = UNSET


class FailureMode(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    label: str
    description: str
    severity: Literal["low", "medium", "high", "blocking"] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET


class SurfaceSuggestion(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    surface_fingerprint: str
    diagnosis: str
    part_label: str | UnsetType = UNSET
    suggested_direction: str | UnsetType = UNSET
    constraints: list[str] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET


class ReflectionResult(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="reflection_result",
    tag_field="role",
):
    schema_version: Literal["leaven.stage_payloads.v1"]
    summary: str
    source_refs: list[InfoRef]
    read_receipts: list[ReceiptRef]
    data_classes: DataClassSet
    failure_modes: list[FailureMode] | UnsetType = UNSET
    surface_suggestions: list[SurfaceSuggestion] | UnsetType = UNSET
    negative_constraints: list[str] | UnsetType = UNSET
    positive_constraints: list[str] | UnsetType = UNSET
    confidence: float | UnsetType = UNSET


class RunnerRequest(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="runner",
    tag_field="role",
):
    schema_version: Literal["leaven.stage_payloads.v1"]
    run: str
    stage_call_id: str
    candidate: CandidateRef
    case: CaseRef
    case_input: WireJsonField
    target_forbidden: bool


type ProposalEffect = Literal[
    "create",
    "change",
    "change_from_workspace_diff",
    "change_from_agent_session",
]


class ProposeRequest(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="proposer",
    tag_field="role",
):
    schema_version: Literal["leaven.stage_payloads.v1"]
    run: str
    stage_call_id: str
    base_revision: str
    parent: CandidateRef
    reflection_result: ReflectionResult
    allowed_effects: list[ProposalEffect]
    capability_fingerprint: str
    surface_fingerprint: str | UnsetType = UNSET
    allowed_change_schemas: list[str] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET
    query_policy_fingerprint: str | UnsetType = UNSET


type StageRunPayload = RunnerRequest | ProposeRequest
type PlanResultStatus = Literal["succeeded", "failed", "cancelled", "timeout"]
type LeavenValueKind = Literal[
    "emit_run_event",
    "graph_set",
    "case_record",
    "workspace_handle",
    "workspace_snapshot",
    "workspace_file",
    "workspace_diff",
    "workspace_listing",
    "lm_response",
    "agent_session",
    "sandbox_exec",
    "proposal_batch_receipt",
    "assessment_batch_receipt",
    "evaluation_request_receipt",
    "apply_receipt",
]
type OperationReceiptKind = Literal["query", "call", "write"]
type CallReceiptKind = Literal[
    "lm_complete", "agent_run", "sandbox_exec", "workspace_materialize", "workspace_release", "extension"
]
type WriteReceiptKind = Literal[
    "submit_proposal_batch",
    "submit_assessments",
    "request_evaluation",
    "apply_proposal_batch",
    "emit_run_event",
]


class LeavenValue(Struct, frozen=True, omit_defaults=True, kw_only=True):
    kind: LeavenValueKind
    graph_revision: str
    data_classes: DataClassSet
    replayability: Replayability
    receipt: ReceiptRef | UnsetType = UNSET
    event_id: str | UnsetType = UNSET
    items: list[GraphRow] | UnsetType = UNSET
    case: ReceiptRef | UnsetType = UNSET
    workspace: str | UnsetType = UNSET
    path: str | UnsetType = UNSET
    status: str | UnsetType = UNSET
    proposal_ids: list[str] | UnsetType = UNSET
    assessment_ids: list[str] | UnsetType = UNSET
    evaluation_request_id: str | UnsetType = UNSET
    created_candidates: list[ReceiptRef] | UnsetType = UNSET
    redactions: list[Redaction] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET


class OperationReceipt(Struct, frozen=True, omit_defaults=True, kw_only=True):
    kind: OperationReceiptKind
    receipt: ReceiptRef
    status: PlanResultStatus
    op_var: str | UnsetType = UNSET
    started_at: str | UnsetType = UNSET
    completed_at: str | UnsetType = UNSET
    error: PlanError | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET
    op_hash: str | UnsetType = UNSET
    result_hash: str
    graph_revision: str | UnsetType = UNSET
    read_scope_fingerprint: str | UnsetType = UNSET
    projection_fingerprint: str | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET
    bytes: int | UnsetType = UNSET
    call_kind: CallReceiptKind | UnsetType = UNSET
    request_hash: str | UnsetType = UNSET
    runtime_fingerprint: str | UnsetType = UNSET
    cost: Cost | UnsetType = UNSET
    charge_receipts: list[str] | UnsetType = UNSET
    write_kind: WriteReceiptKind | UnsetType = UNSET
    base_revision: str | UnsetType = UNSET
    committed_revision: str | UnsetType = UNSET
    proposal_batch_id: str | UnsetType = UNSET
    proposal_ids: list[str] | UnsetType = UNSET
    evaluation_request_id: str | UnsetType = UNSET
    assessment_ids: list[str] | UnsetType = UNSET
    created_candidates: list[ReceiptRef] | UnsetType = UNSET
    event_id: str | UnsetType = UNSET
    preconditions: list[WireJsonObject] | UnsetType = UNSET
    validation_receipts: list[WireJsonObject] | UnsetType = UNSET


class ChargeReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    receipt: str
    source_receipt: ReceiptRef
    cost: Cost
    charged_at: str
    ledger_scope: str | UnsetType = UNSET


class PlanDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    schema_version: Literal["leaven.plan.v1"]
    plan_id: str
    consistency: Consistency
    mode: EvalMode
    ops: list[PlanOp]
    return_: list[str] = field(name="return")
    commit: CommitPolicy
    metadata: MetadataBag | UnsetType = UNSET


class PlanResultDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    schema_version: Literal["leaven.plan_result.v1"]
    plan_id: str
    capability_fingerprint: str
    policy_fingerprint: str
    base_revision: str
    final_revision: str
    replayability_summary: Replayability
    values: dict[str, LeavenValue]
    receipts: list[OperationReceipt]
    redactions: list[Redaction]
    charges: list[ChargeReceipt]
    errors: list[PlanError]
    metadata: MetadataBag | UnsetType = UNSET


type StageRunKind = Literal["runner"] | Literal["proposer"]


class StageRunRequest(Struct, frozen=True, forbid_unknown_fields=True):
    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_request"]
    stage: StageRunKind
    payload: StageRunPayload


class StageRunResult(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_result"]
    stage: StageRunKind
    stage_call_id: str
    output: OutputRecord
    effect_receipts: list[StageEffectReceipt] | UnsetType = UNSET
    proposal_receipts: list[StageProposalReceipt] | UnsetType = UNSET


__all__ = (  # noqa: PLE0605, SIM905
    "PLAN_RESULT_SCHEMA_FINGERPRINT PLAN_SCHEMA_FINGERPRINT STAGE_RUN_SCHEMA_FINGERPRINT "
    "{REF_EXPORTS} "
    "AssessmentSummaryGraphRow BlobRef "
    "CandidateSummaryGraphRow CapabilityCall ChargeReceipt CommitPolicy CommitPolicyGraphWritesAtomic "
    "CommitPolicyGraphWritesSequential CommitPolicyNoGraphWrites Consistency ConsistencyAtRevision "
    "ConsistencyLatestAtStart ConsistencySinceRevision Cost DataClassSet EvalMode EvalModeDryRun "
    "EvalModeExecute EvalModeReplay EvalModeRequireCached EventSummaryGraphRow ExtensionGraphRow FailureMode "
    "GraphRow GraphWrite InfoRef LeavenValue MetadataBag OperationReceipt OutputRecord PlanDocument "
    "PlanError PlanOp PlanResultDocument ProposalBatchRef ProposalBatchRefRecord ProposalEffect ProposeRequest "
    "ProposalRef ProposalRefRecord ProposalSummaryGraphRow ReceiptRef Redaction ReflectionResult Replayability "
    "RunnerRequest Score "
    "StageEffectReceipt StageProposalReceipt StageRunKind StageRunPayload StageRunRequest StageRunResult "
    "StaleWritePolicy SurfaceSuggestion TraceRef VisibilityClass WireJsonField WireJsonLeafArray "
    "WireJsonLeafObject WireJsonObject WireJsonScalar"
).split()
'''
