"""Render generated Plan graph-write records for public-seam payloads."""

WRITE_EXPORTS = (
    "ApplyProposalBatchWrite AttributionCost CostAttribution EmitRunEventWrite "
    "EvaluationRequestWriteRecord GraphWrite ProposalEffectAgentSession ProposalEffectChange "
    "ProposalEffectCreate ProposalEffectWorkspaceDiff ProposalEffectWrite ProposalWriteRecord "
    "RequestEvaluationWrite SubmitAssessmentRecord SubmitAssessmentsWrite SubmitProposalBatchWrite "
    "WriteOutputRecord WriteScore"
)


def render_writes() -> str:
    """Render generated Plan graph-write records as their own private wire module."""
    return f'''"""Generated public-seam Plan graph-write records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType

from .expressions import PlanExpression, ValueExpr
from .refs import (
    CandidateRef,
    DataClassSet,
    MetadataBag,
    ProposalBatchRef,
    ReceiptRef,
    WireJsonField,
    WireJsonObject,
    WorkspaceRef,
)

type Replayability = Literal[
    "pure_read",
    "fully_managed",
    "boundary_managed",
    "has_declared_external_effects",
    "has_untracked_external_effects",
]

type VisibilityClass = Literal[
    "public",
    "optimizer_visible",
    "reflector_visible",
    "evaluator_only",
    "operator_only",
    "private",
    "redacted",
]


class ProposalEffectCreate(Struct, frozen=True, forbid_unknown_fields=True, tag="create", tag_field="kind"):
    artifact_type: str
    artifact_schema: str
    artifact: ValueExpr


class ProposalEffectChange(Struct, frozen=True, forbid_unknown_fields=True, tag="change", tag_field="kind"):
    target: CandidateRef
    surface_fingerprint: str
    change_schema: str
    change: ValueExpr


class ProposalEffectWorkspaceDiff(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="change_from_workspace_diff", tag_field="kind"):
    target: CandidateRef
    workspace: WorkspaceRef
    surface_fingerprint: str
    change_schema: str
    roots: list[str] | UnsetType = UNSET
    parser: str | UnsetType = UNSET


class ProposalEffectAgentSession(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="change_from_agent_session", tag_field="kind"):
    target: CandidateRef
    agent_receipt: ReceiptRef
    parser: str
    surface_fingerprint: str
    change_schema: str


type ProposalEffectWrite = (
    ProposalEffectCreate
    | ProposalEffectChange
    | ProposalEffectWorkspaceDiff
    | ProposalEffectAgentSession
)


class ProposalWriteRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    effect: ProposalEffectWrite
    causal: WireJsonObject
    informed_by: PlanExpression
    annotations: ValueExpr | UnsetType = UNSET
    annotations_schema: str | UnsetType = UNSET
    read_receipts: list[ReceiptRef] | UnsetType = UNSET
    metadata: MetadataBag | UnsetType = UNSET


class SubmitProposalBatchWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="submit_proposal_batch", tag_field="kind"):
    semantics: Literal["alternatives", "sequence"]
    proposals: list[ProposalWriteRecord]


class WriteOutputRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    kind: Literal["text", "json", "blob_ref", "structured", "agent_session", "workspace_diff"]
    visibility: VisibilityClass
    data_classes: DataClassSet
    summary: str | UnsetType = UNSET
    value: WireJsonField | UnsetType = UNSET
    blob_ref: WireJsonObject | UnsetType = UNSET
    trace_refs: list[WireJsonObject] | UnsetType = UNSET


class WriteScore(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    value: float
    output: WriteOutputRecord
    metrics: dict[str, float] | UnsetType = UNSET
    uncertainty: float | UnsetType = UNSET
    metadata: MetadataBag | UnsetType = UNSET


class AttributionCost(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    usd_micro: int | UnsetType = UNSET
    input_tokens: int | UnsetType = UNSET
    output_tokens: int | UnsetType = UNSET
    lm_calls: int | UnsetType = UNSET
    agent_calls: int | UnsetType = UNSET
    sandbox_calls: int | UnsetType = UNSET
    metric_calls: int | UnsetType = UNSET
    wall_ms: int | UnsetType = UNSET


class CostAttribution(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    kind: Literal["sum_effect_receipts", "explicit", "none"]
    cost: AttributionCost | UnsetType = UNSET


class SubmitAssessmentRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    kind: Literal["independent", "pairwise", "listwise"]
    score: WriteScore
    evidence: WireJsonObject
    replayability: Replayability
    candidate: CandidateRef | UnsetType = UNSET
    candidates: list[CandidateRef] | UnsetType = UNSET
    target: WireJsonField | UnsetType = UNSET
    preference: WireJsonField | UnsetType = UNSET
    ranking: WireJsonField | UnsetType = UNSET
    read_receipts: list[ReceiptRef] | UnsetType = UNSET
    effect_receipts: list[ReceiptRef] | UnsetType = UNSET
    cost_attribution: CostAttribution | UnsetType = UNSET


class SubmitAssessmentsWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="submit_assessments", tag_field="kind"):
    evaluation_request_id: str
    assessments: list[SubmitAssessmentRecord]


class EvaluationRequestWriteRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    shape: Literal["independent", "pairwise", "listwise"]
    candidates: list[CandidateRef]
    set: WireJsonObject
    granularity: Literal["aggregate", "per_case"]
    purpose: Literal["train", "validation", "test", "diagnostic", "custom"]
    evaluator: str | UnsetType = UNSET
    metadata: MetadataBag | UnsetType = UNSET


class RequestEvaluationWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="request_evaluation", tag_field="kind"):
    request: EvaluationRequestWriteRecord


class ApplyProposalBatchWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="apply_proposal_batch", tag_field="kind"):
    proposal_batch: ProposalBatchRef
    policy: Literal["apply_all", "apply_first_valid", "apply_by_optimizer_policy"]


class EmitRunEventWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="emit_run_event", tag_field="kind"):
    event_kind: str
    payload_schema: str
    payload: WireJsonField
    visibility: VisibilityClass


type GraphWrite = (
    SubmitProposalBatchWrite
    | SubmitAssessmentsWrite
    | RequestEvaluationWrite
    | ApplyProposalBatchWrite
    | EmitRunEventWrite
)


__all__ = (  # noqa: PLE0605, SIM905
    "{WRITE_EXPORTS}"
).split()
'''
