"""Generated public-seam Plan capability-call records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType

from .refs import (
    CandidateRef,
    DataClassSet,
    WireJsonField,
    WireJsonObject,
    WireJsonSchemaObject,
    WorkspaceRef,
)

type StreamPolicy = Literal["buffer", "stream_updates", "blob_refs_only"]
type WorkspaceLifetime = Literal["plan", "stage_call", "manual_release"]
type WorkspaceMaterializeMode = Literal["read_only", "copy_on_write", "mutable_eval"]


class OutputFinalMessage(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="final_message", tag_field="kind"):
    max_bytes: int | UnsetType = UNSET


class OutputJsonSchema(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="json_schema", tag_field="kind"):
    schema_fingerprint: str
    schema: WireJsonSchemaObject | UnsetType = UNSET


class OutputFiles(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="files", tag_field="kind"):
    paths: list[str]
    max_bytes: int | UnsetType = UNSET


class OutputWorkspaceDiff(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="workspace_diff", tag_field="kind"):
    surface_fingerprint: str
    max_bytes: int | UnsetType = UNSET


type OutputContract = OutputFinalMessage | OutputJsonSchema | OutputFiles | OutputWorkspaceDiff


class LmOutputFinalMessage(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="final_message", tag_field="kind"):
    max_bytes: int | UnsetType = UNSET


class LmOutputJsonSchema(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="json_schema", tag_field="kind"):
    schema_fingerprint: str
    schema: WireJsonSchemaObject | UnsetType = UNSET


type LmOutputContract = LmOutputFinalMessage | LmOutputJsonSchema


class LmContentText(Struct, frozen=True, forbid_unknown_fields=True, tag="text", tag_field="kind"):
    text: str


class LmContentToolResult(Struct, frozen=True, forbid_unknown_fields=True, tag="tool_result", tag_field="kind"):
    tool_call_id: str
    content: str


type LmContentPart = LmContentText | LmContentToolResult
type LmMessageRole = Literal["system", "developer", "user", "assistant", "tool"]


class LmMessage(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    role: LmMessageRole
    content: list[LmContentPart]
    tool_call_id: str | UnsetType = UNSET
    name: str | UnsetType = UNSET


class LmTool(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    name: str
    input_schema: WireJsonField
    description: str | UnsetType = UNSET
    requires_capability_action: str | UnsetType = UNSET


class LmSampling(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    temperature: float | UnsetType = UNSET
    top_p: float | UnsetType = UNSET
    max_output_tokens: int | UnsetType = UNSET
    seed: int | UnsetType = UNSET
    stop: list[str] | UnsetType = UNSET


class LmCompleteCall(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="lm_complete", tag_field="kind"):
    purpose: str
    messages: list[LmMessage]
    output: LmOutputContract
    input_classes: DataClassSet
    model: str | UnsetType = UNSET
    model_role: str | UnsetType = UNSET
    tools: list[LmTool] | UnsetType = UNSET
    sampling: LmSampling | UnsetType = UNSET
    provider_hints: WireJsonObject | UnsetType = UNSET
    cache_policy: Literal["default", "require_cached", "bypass", "record_only"] | UnsetType = UNSET
    forbidden_input_classes: DataClassSet | UnsetType = UNSET


class AgentInstructions(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    task: str
    system: str | UnsetType = UNSET


class AgentToolPolicy(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    allow_shell: bool | UnsetType = UNSET
    allowed_tools: list[str] | UnsetType = UNSET
    denied_tools: list[str] | UnsetType = UNSET
    allowed_commands: list[str] | UnsetType = UNSET
    deny_paths: list[str] | UnsetType = UNSET
    network: Literal["deny", "leaven_endpoint_only", "allowlist", "unrestricted"] | UnsetType = UNSET


class AgentLimits(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    timeout_s: int | UnsetType = UNSET
    max_turns: int | UnsetType = UNSET
    max_usd_micro: int | UnsetType = UNSET


class AgentRunCall(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="agent_run", tag_field="kind"):
    runtime: str
    instructions: AgentInstructions
    output: OutputContract
    input_classes: DataClassSet
    runtime_fingerprint: str | UnsetType = UNSET
    workspace: WorkspaceRef | UnsetType = UNSET
    tool_policy: AgentToolPolicy | UnsetType = UNSET
    limits: AgentLimits | UnsetType = UNSET
    forbidden_input_classes: DataClassSet | UnsetType = UNSET


class SandboxExecCall(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="sandbox_exec", tag_field="kind"):
    workspace: WorkspaceRef
    argv: list[str]
    timeout_s: int
    output: OutputContract
    input_classes: DataClassSet
    cwd: str | UnsetType = UNSET
    env: dict[str, str] | UnsetType = UNSET
    stream_policy: StreamPolicy | UnsetType = UNSET
    forbidden_input_classes: DataClassSet | UnsetType = UNSET


class WorkspaceMaterializeCall(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="workspace_materialize", tag_field="kind"):
    candidate: CandidateRef
    mode: WorkspaceMaterializeMode
    lifetime: WorkspaceLifetime
    surface: str | UnsetType = UNSET


class WorkspaceReleaseCall(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="workspace_release", tag_field="kind"):
    workspace: WorkspaceRef
    force: bool | UnsetType = UNSET


type CapabilityCall = (
    LmCompleteCall
    | AgentRunCall
    | SandboxExecCall
    | WorkspaceMaterializeCall
    | WorkspaceReleaseCall
)


__all__ = (  # noqa: PLE0605, SIM905
    "AgentInstructions AgentLimits AgentRunCall AgentToolPolicy CapabilityCall LmCompleteCall LmContentPart LmContentText LmContentToolResult LmMessage LmMessageRole LmOutputContract LmOutputFinalMessage LmOutputJsonSchema LmSampling LmTool OutputContract OutputFiles OutputFinalMessage OutputJsonSchema OutputWorkspaceDiff SandboxExecCall StreamPolicy WorkspaceLifetime WorkspaceMaterializeCall WorkspaceMaterializeMode WorkspaceReleaseCall"
).split()
