"""Generated public-seam evidence envelope records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

import msgspec
from msgspec import UNSET, Raw, Struct, UnsetType

from .refs import (
    BlobRef,
    DataClassSet,
    MetadataBag,
    ReceiptRef,
    TraceRef,
)

type EvidenceVisibility = Literal[
    "none",
    "score_only",
    "score_and_feedback",
    "score_feedback_and_rationale",
    "full",
]


class EvidenceProducer(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    stage_call_id: str
    evaluator_id: str | UnsetType = UNSET
    evaluator_fingerprint: str | UnsetType = UNSET


class EvidencePublic(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    data_classes: DataClassSet
    feedback: str | UnsetType = UNSET
    summary: str | UnsetType = UNSET
    metrics: dict[str, float] | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET


class EvidencePrivate(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    visibility: Literal["evaluator_only", "operator_only", "scorer_private"]
    data_classes: DataClassSet
    payload: Raw | UnsetType = UNSET
    payload_ref: BlobRef | UnsetType = UNSET
    payload_schema_fingerprint: str | UnsetType = UNSET


class EvidenceRedactionPolicy(Struct, frozen=True, forbid_unknown_fields=True):
    optimizer: EvidenceVisibility
    reflector: EvidenceVisibility
    operator: EvidenceVisibility


class EvidenceSourceReceipts(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    read: list[ReceiptRef]
    effect: list[ReceiptRef]
    write: list[ReceiptRef] | UnsetType = UNSET


class EvidenceEnvelope(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    schema_version: Literal["leaven.evidence_envelope.v1"]
    target_derived: bool
    public: EvidencePublic
    redaction_policy: EvidenceRedactionPolicy
    producer: EvidenceProducer
    source_receipts: EvidenceSourceReceipts
    data_classes: DataClassSet | UnsetType = UNSET
    private: EvidencePrivate | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET
    replayability: Literal[
        "pure_read",
        "fully_managed",
        "boundary_managed",
        "has_declared_external_effects",
        "has_untracked_external_effects",
    ] | UnsetType = UNSET
    metadata: MetadataBag | UnsetType = UNSET


def decode_evidence_private_payload[T](private: EvidencePrivate, payload_type: type[T]) -> T:
    """Decode schema-selected private evidence payload bytes into a caller-owned type."""
    if private.payload is UNSET:
        raise ValueError("evidence private payload is absent")
    return msgspec.json.decode(private.payload, type=payload_type)


__all__ = (  # noqa: PLE0605, SIM905
    "EvidenceEnvelope EvidencePrivate EvidenceProducer EvidencePublic EvidenceRedactionPolicy EvidenceSourceReceipts EvidenceVisibility decode_evidence_private_payload"
).split()
