"""Generated public-seam graph-row records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType

from .evidence import EvidenceEnvelope
from .refs import (
    AssessmentRef,
    BlobRef,
    CandidateRef,
    DataClassSet,
    EventSummaryPayload,
    MetadataBag,
    ProposalBatchRef,
    ProposalRef,
    ReceiptRef,
    TraceRef,
    WireJsonGraphExtensionPayload,
    WireJsonOutputValue,
    WorkspaceRef,
)

type VisibilityClass = Literal[
    "public",
    "optimizer_visible",
    "reflector_visible",
    "evaluator_only",
    "operator_only",
    "private",
    "redacted",
]


class OutputRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    kind: Literal["text", "json", "blob_ref", "structured", "agent_session", "workspace_diff"]
    visibility: VisibilityClass
    data_classes: DataClassSet
    summary: str | UnsetType = UNSET
    value: WireJsonOutputValue | UnsetType = UNSET
    blob_ref: BlobRef | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET


class Score(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    value: float
    output: OutputRecord
    metrics: dict[str, float] | UnsetType = UNSET
    uncertainty: float | UnsetType = UNSET
    metadata: MetadataBag | UnsetType = UNSET


class CandidateCaseScore(Struct, frozen=True, forbid_unknown_fields=True):
    case: str
    score: float


class CandidateScoresSummary(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    primary: float | UnsetType = UNSET
    metrics: dict[str, float] | UnsetType = UNSET
    cases: list[CandidateCaseScore] | UnsetType = UNSET


class CandidateArtifactSummary(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    kind: str
    identity: str | UnsetType = UNSET
    summary: str | UnsetType = UNSET
    body: str | UnsetType = UNSET
    schema_fingerprint: str | UnsetType = UNSET


class CandidateSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="candidate_summary",
    tag_field="kind",
):
    candidate: CandidateRef
    artifact_identity: str | UnsetType = UNSET
    scores: CandidateScoresSummary | UnsetType = UNSET
    artifact: CandidateArtifactSummary | UnsetType = UNSET


type ProposalEffectSummaryKind = Literal[
    "create",
    "change",
    "change_from_workspace_diff",
    "change_from_agent_session",
]


class ProposalEffectSummary(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    kind: ProposalEffectSummaryKind
    target: CandidateRef | UnsetType = UNSET
    artifact_type: str | UnsetType = UNSET
    artifact_schema: str | UnsetType = UNSET
    workspace: WorkspaceRef | UnsetType = UNSET
    agent_receipt: ReceiptRef | UnsetType = UNSET
    parser: str | UnsetType = UNSET
    surface_fingerprint: str | UnsetType = UNSET
    change_schema: str | UnsetType = UNSET


class ProposalSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="proposal_summary",
    tag_field="kind",
):
    proposal: ProposalRef
    batch: ProposalBatchRef | UnsetType = UNSET
    effect: ProposalEffectSummary | UnsetType = UNSET


class AssessmentSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="assessment_summary",
    tag_field="kind",
):
    assessment: AssessmentRef
    score: Score
    evidence: EvidenceEnvelope


class EventSummaryGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="event_summary",
    tag_field="kind",
):
    event_kind: str
    revision: str
    payload: EventSummaryPayload | UnsetType = UNSET


class ExtensionGraphRow(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="extension",
    tag_field="kind",
):
    namespace: str
    op: str
    schema_fingerprint: str
    payload: WireJsonGraphExtensionPayload


type GraphRow = (
    CandidateSummaryGraphRow
    | ProposalSummaryGraphRow
    | AssessmentSummaryGraphRow
    | EventSummaryGraphRow
    | ExtensionGraphRow
)


__all__ = (  # noqa: PLE0605, SIM905
    "AssessmentSummaryGraphRow CandidateArtifactSummary CandidateCaseScore CandidateScoresSummary CandidateSummaryGraphRow EventSummaryGraphRow ExtensionGraphRow "
    "GraphRow OutputRecord ProposalEffectSummary ProposalEffectSummaryKind ProposalSummaryGraphRow "
    "Score VisibilityClass"
).split()
