"""Generated locked public-seam V1 method metadata.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal, cast

from msgspec import Struct

type LockedMethod = (
    Literal["leaven/stage.run"]
    | Literal["leaven/graph.query"]
    | Literal["leaven/case.load"]
    | Literal["leaven/case.input"]
    | Literal["leaven/case.target"]
    | Literal["leaven/case.metadata"]
    | Literal["leaven/workspace.materialize"]
    | Literal["leaven/workspace.snapshot"]
    | Literal["leaven/workspace.list"]
    | Literal["leaven/workspace.read_file"]
    | Literal["leaven/workspace.stat"]
    | Literal["leaven/workspace.digest"]
    | Literal["leaven/workspace.git_log"]
    | Literal["leaven/workspace.git_diff"]
    | Literal["leaven/workspace.git_status"]
    | Literal["leaven/workspace.capture_artifacts"]
    | Literal["leaven/workspace.release"]
    | Literal["leaven/lm.complete"]
    | Literal["leaven/agent.run"]
    | Literal["leaven/sandbox.exec"]
    | Literal["leaven/proposal.submit_batch"]
    | Literal["leaven/proposal.apply"]
    | Literal["leaven/assessment.submit"]
    | Literal["leaven/evaluation.request"]
    | Literal["leaven/event.emit"]
)


class LockedMethodBinding(Struct, frozen=True, forbid_unknown_fields=True):
    """A generated public-seam method/profile binding."""

    method: LockedMethod
    params_schema: str
    result_schema: str
    required_action: str
    params_schema_fingerprint: str
    result_schema_fingerprint: str
    produces_receipt: bool


LOCKED_METHODS: tuple[LockedMethod, ...] = (
    "leaven/stage.run",
    "leaven/graph.query",
    "leaven/case.load",
    "leaven/case.input",
    "leaven/case.target",
    "leaven/case.metadata",
    "leaven/workspace.materialize",
    "leaven/workspace.snapshot",
    "leaven/workspace.list",
    "leaven/workspace.read_file",
    "leaven/workspace.stat",
    "leaven/workspace.digest",
    "leaven/workspace.git_log",
    "leaven/workspace.git_diff",
    "leaven/workspace.git_status",
    "leaven/workspace.capture_artifacts",
    "leaven/workspace.release",
    "leaven/lm.complete",
    "leaven/agent.run",
    "leaven/sandbox.exec",
    "leaven/proposal.submit_batch",
    "leaven/proposal.apply",
    "leaven/assessment.submit",
    "leaven/evaluation.request",
    "leaven/event.emit",
)

METHOD_BINDINGS: tuple[LockedMethodBinding, ...] = (
    LockedMethodBinding(
        method="leaven/stage.run",
        params_schema="leaven.stage_run.v1.schema.json",
        result_schema="leaven.stage_run.v1.schema.json",
        required_action="stage.run",
        params_schema_fingerprint="fp_schema_sha256_860ddd5b1831bb09b54fbbe10bc68e87126bedbee3eaa31c4a2754d999c2275a",
        result_schema_fingerprint="fp_schema_sha256_860ddd5b1831bb09b54fbbe10bc68e87126bedbee3eaa31c4a2754d999c2275a",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/graph.query",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="graph.query",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/case.load",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="case.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/case.input",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="case.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/case.target",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="case.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/case.metadata",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="case.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.materialize",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.materialize",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.snapshot",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.list",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.read_file",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.stat",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.digest",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.git_log",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.git_diff",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.git_status",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.capture_artifacts",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.read",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/workspace.release",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="workspace.release",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/lm.complete",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="lm.complete",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/agent.run",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="agent.run",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/sandbox.exec",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="sandbox.exec",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/proposal.submit_batch",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="proposal.submit_batch",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/proposal.apply",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="proposal.apply_batch",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/assessment.submit",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="assessment.submit",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/evaluation.request",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="evaluation.request",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
    LockedMethodBinding(
        method="leaven/event.emit",
        params_schema="leaven.plan.v1.schema.json",
        result_schema="leaven.plan_result.v1.schema.json",
        required_action="event.emit",
        params_schema_fingerprint="fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680",
        result_schema_fingerprint="fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3",
        produces_receipt=True,
    ),
)

_METHOD_BINDING_BY_NAME: dict[str, LockedMethodBinding] = {
    binding.method: binding for binding in METHOD_BINDINGS
}


def require_locked_method(method: str) -> LockedMethod:
    """Return `method` as a locked V1 method or raise `ValueError`."""
    if method not in _METHOD_BINDING_BY_NAME:
        raise ValueError(f"unknown locked Leaven public-seam method: {method}")
    return cast("LockedMethod", method)


__all__ = [
    "LOCKED_METHODS",
    "METHOD_BINDINGS",
    "LockedMethod",
    "LockedMethodBinding",
    "require_locked_method",
]
