"""Generated top-level public-seam payload records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Raw, Struct, UnsetType, field

PLAN_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680"
)
PLAN_RESULT_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3"
)
STAGE_RUN_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_860ddd5b1831bb09b54fbbe10bc68e87126bedbee3eaa31c4a2754d999c2275a"
)


class PlanDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.plan.v1` payload with nested operation bodies kept raw."""

    schema_version: Literal["leaven.plan.v1"]
    plan_id: str
    consistency: Raw
    mode: Raw
    ops: Raw
    return_: Raw = field(name="return")
    commit: Raw
    metadata: Raw | UnsetType = UNSET


class PlanResultDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.plan_result.v1` result with nested values kept raw."""

    schema_version: Literal["leaven.plan_result.v1"]
    plan_id: str
    capability_fingerprint: str
    policy_fingerprint: str
    base_revision: str
    final_revision: str
    replayability_summary: Raw
    values: Raw
    receipts: Raw
    redactions: Raw
    charges: Raw
    errors: Raw
    metadata: Raw | UnsetType = UNSET


type StageRunKind = Literal["runner"] | Literal["proposer"]


class StageRunRequest(Struct, frozen=True, forbid_unknown_fields=True):
    """Top-level `leaven.stage_run.v1` request with role payload kept raw."""

    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_request"]
    stage: StageRunKind
    payload: Raw


class StageRunResult(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.stage_run.v1` result with output and receipts kept raw."""

    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_result"]
    stage: StageRunKind
    stage_call_id: str
    output: Raw
    effect_receipts: Raw | UnsetType = UNSET
    proposal_receipts: Raw | UnsetType = UNSET


__all__ = [
    "PLAN_RESULT_SCHEMA_FINGERPRINT",
    "PLAN_SCHEMA_FINGERPRINT",
    "STAGE_RUN_SCHEMA_FINGERPRINT",
    "PlanDocument",
    "PlanResultDocument",
    "StageRunKind",
    "StageRunRequest",
    "StageRunResult",
]
