"""Generated top-level public-seam payload records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType, field

PLAN_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_dec4dc30152389ce0121e8c3b008a3c9eca02a1c27a14a8ed3df2f79d0f8e680"
)
PLAN_RESULT_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_2dabfac70fb80e32fe0f5b5e3259fb21677da427bd268b87979fd0ce3a5155d3"
)
STAGE_RUN_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_860ddd5b1831bb09b54fbbe10bc68e87126bedbee3eaa31c4a2754d999c2275a"
)


type WireJsonScalar = str | int | float | bool | None
type WireJsonLeafArray = list[WireJsonScalar]
type WireJsonLeafObject = dict[str, WireJsonScalar | WireJsonLeafArray]
type WireJsonField = WireJsonScalar | WireJsonLeafArray | WireJsonLeafObject
type WireJsonObject = dict[str, WireJsonField]

type DataClassSet = list[str]
type InfoRef = str | WireJsonObject
type MetadataBag = WireJsonObject
type ReceiptRef = str | WireJsonObject
type Replayability = Literal[
    "pure_read",
    "fully_managed",
    "boundary_managed",
    "has_declared_external_effects",
    "has_untracked_external_effects",
]
type TraceRef = WireJsonObject


class ConsistencyLatestAtStart(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="latest_at_start",
    tag_field="kind",
):
    """Plan consistency pinned to the latest graph revision at plan start."""


class ConsistencyAtRevision(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="at_revision",
    tag_field="kind",
):
    """Plan consistency pinned to one graph revision."""

    revision: str


class ConsistencySinceRevision(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="since_revision",
    tag_field="kind",
):
    """Plan consistency pinned to a revision range."""

    since: str
    until: str | UnsetType = UNSET


type Consistency = ConsistencyLatestAtStart | ConsistencyAtRevision | ConsistencySinceRevision


class EvalModeExecute(Struct, frozen=True, forbid_unknown_fields=True, tag="execute", tag_field="kind"):
    """Execute plan effects."""


class EvalModeDryRun(Struct, frozen=True, forbid_unknown_fields=True, tag="dry_run", tag_field="kind"):
    """Validate and plan without committing effects."""


class EvalModeRequireCached(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="require_cached",
    tag_field="kind",
):
    """Execute only operations with reusable cached receipts."""


class EvalModeReplay(Struct, frozen=True, forbid_unknown_fields=True, tag="replay", tag_field="kind"):
    """Replay from explicit receipts."""

    receipts: list[ReceiptRef]


type EvalMode = EvalModeExecute | EvalModeDryRun | EvalModeRequireCached | EvalModeReplay


class CommitPolicyNoGraphWrites(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="no_graph_writes",
    tag_field="kind",
):
    """Forbid graph writes."""


type StaleWritePolicy = Literal["reject", "allow_if_policy_allows", "rebase_extension"]


class CommitPolicyGraphWritesAtomic(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="graph_writes_atomic",
    tag_field="kind",
):
    """Commit graph writes atomically."""

    on_stale: StaleWritePolicy


class CommitPolicyGraphWritesSequential(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="graph_writes_sequential",
    tag_field="kind",
):
    """Commit graph writes sequentially."""

    on_failure: Literal["stop", "continue"]
    on_stale: StaleWritePolicy


type CommitPolicy = (
    CommitPolicyNoGraphWrites | CommitPolicyGraphWritesAtomic | CommitPolicyGraphWritesSequential
)
type PlanOp = WireJsonObject


class Cost(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Leaven wire cost record."""

    usd_micro: int | UnsetType = UNSET
    input_tokens: int | UnsetType = UNSET
    output_tokens: int | UnsetType = UNSET
    lm_calls: int | UnsetType = UNSET
    agent_calls: int | UnsetType = UNSET
    sandbox_calls: int | UnsetType = UNSET
    metric_calls: int | UnsetType = UNSET
    wall_ms: int | UnsetType = UNSET


class BlobRef(Struct, frozen=True, forbid_unknown_fields=True, tag="blob_ref", tag_field="kind"):
    """Blob reference from common public-seam schema."""

    id: str
    sha256: str
    bytes: int
    data_classes: DataClassSet
    media_type: str | UnsetType = UNSET
    uri: str | UnsetType = UNSET


type VisibilityClass = Literal[
    "public",
    "optimizer_visible",
    "reflector_visible",
    "evaluator_only",
    "operator_only",
    "private",
    "redacted",
]


class OutputRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Reportable stage or score output."""

    kind: Literal["text", "json", "blob_ref", "structured", "agent_session", "workspace_diff"]
    visibility: VisibilityClass
    data_classes: DataClassSet
    summary: str | UnsetType = UNSET
    value: WireJsonField | UnsetType = UNSET
    blob_ref: BlobRef | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET


class Redaction(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Redaction marker from common public-seam schema."""

    path: str
    reason: str
    policy_fingerprint: str | UnsetType = UNSET
    public_reason: str | UnsetType = UNSET
    audit_reason: str | UnsetType = UNSET


class PlanError(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Plan error from common public-seam schema."""

    code: str
    message: str
    op: str | UnsetType = UNSET
    path: str | UnsetType = UNSET
    receipt: ReceiptRef | UnsetType = UNSET
    retryable: bool | UnsetType = UNSET
    details: WireJsonField | UnsetType = UNSET


class StageCost(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Stage effect receipt cost subset."""

    usd_micro: int | UnsetType = UNSET
    input_tokens: int | UnsetType = UNSET
    output_tokens: int | UnsetType = UNSET
    lm_calls: int | UnsetType = UNSET


class StageEffectReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Receipt for LM or agent calls made by a stage."""

    method: Literal["leaven/lm.complete", "leaven/agent.run"]
    receipt: str
    call_kind: Literal["lm_complete", "agent_run"] | UnsetType = UNSET
    cost: StageCost | UnsetType = UNSET
    blob_refs: list[BlobRef] | UnsetType = UNSET


class StageProposalReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Receipt for proposal submission made by a stage."""

    method: Literal["leaven/proposal.submit_batch"]
    receipt: ReceiptRef
    write_kind: Literal["submit_proposal_batch"] | UnsetType = UNSET
    proposal_ids: list[str] | UnsetType = UNSET


class FailureMode(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Reflection failure mode."""

    label: str
    description: str
    severity: Literal["low", "medium", "high", "blocking"] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET


class SurfaceSuggestion(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Reflection surface suggestion."""

    surface_fingerprint: str
    diagnosis: str
    part_label: str | UnsetType = UNSET
    suggested_direction: str | UnsetType = UNSET
    constraints: list[str] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET


class ReflectionResult(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="reflection_result",
    tag_field="role",
):
    """Reflection result stage payload."""

    schema_version: Literal["leaven.stage_payloads.v1"]
    summary: str
    source_refs: list[InfoRef]
    read_receipts: list[ReceiptRef]
    data_classes: DataClassSet
    failure_modes: list[FailureMode] | UnsetType = UNSET
    surface_suggestions: list[SurfaceSuggestion] | UnsetType = UNSET
    negative_constraints: list[str] | UnsetType = UNSET
    positive_constraints: list[str] | UnsetType = UNSET
    confidence: float | UnsetType = UNSET


class RunnerRequest(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="runner",
    tag_field="role",
):
    """Runner stage payload."""

    schema_version: Literal["leaven.stage_payloads.v1"]
    run: str
    stage_call_id: str
    candidate: str | WireJsonObject
    case: str | WireJsonObject
    case_input: WireJsonField
    target_forbidden: bool


type ProposalEffect = Literal[
    "create",
    "change",
    "change_from_workspace_diff",
    "change_from_agent_session",
]


class ProposeRequest(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="proposer",
    tag_field="role",
):
    """Proposer stage payload."""

    schema_version: Literal["leaven.stage_payloads.v1"]
    run: str
    stage_call_id: str
    base_revision: str
    parent: str | WireJsonObject
    reflection_result: ReflectionResult
    allowed_effects: list[ProposalEffect]
    capability_fingerprint: str
    surface_fingerprint: str | UnsetType = UNSET
    allowed_change_schemas: list[str] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET
    query_policy_fingerprint: str | UnsetType = UNSET


type StageRunPayload = RunnerRequest | ProposeRequest
type LeavenValue = WireJsonObject
type OperationReceipt = WireJsonObject


class ChargeReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Charge receipt from the plan result schema."""

    receipt: str
    source_receipt: ReceiptRef
    cost: Cost
    charged_at: str
    ledger_scope: str | UnsetType = UNSET


class PlanDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.plan.v1` payload."""

    schema_version: Literal["leaven.plan.v1"]
    plan_id: str
    consistency: Consistency
    mode: EvalMode
    ops: list[PlanOp]
    return_: list[str] = field(name="return")
    commit: CommitPolicy
    metadata: MetadataBag | UnsetType = UNSET


class PlanResultDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.plan_result.v1` result."""

    schema_version: Literal["leaven.plan_result.v1"]
    plan_id: str
    capability_fingerprint: str
    policy_fingerprint: str
    base_revision: str
    final_revision: str
    replayability_summary: Replayability
    values: dict[str, LeavenValue]
    receipts: list[OperationReceipt]
    redactions: list[Redaction]
    charges: list[ChargeReceipt]
    errors: list[PlanError]
    metadata: MetadataBag | UnsetType = UNSET


type StageRunKind = Literal["runner"] | Literal["proposer"]


class StageRunRequest(Struct, frozen=True, forbid_unknown_fields=True):
    """Top-level `leaven.stage_run.v1` request."""

    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_request"]
    stage: StageRunKind
    payload: StageRunPayload


class StageRunResult(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    """Top-level `leaven.stage_run.v1` result."""

    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_result"]
    stage: StageRunKind
    stage_call_id: str
    output: OutputRecord
    effect_receipts: list[StageEffectReceipt] | UnsetType = UNSET
    proposal_receipts: list[StageProposalReceipt] | UnsetType = UNSET


__all__ = [
    "PLAN_RESULT_SCHEMA_FINGERPRINT",
    "PLAN_SCHEMA_FINGERPRINT",
    "STAGE_RUN_SCHEMA_FINGERPRINT",
    "BlobRef",
    "ChargeReceipt",
    "CommitPolicy",
    "CommitPolicyGraphWritesAtomic",
    "CommitPolicyGraphWritesSequential",
    "CommitPolicyNoGraphWrites",
    "Consistency",
    "ConsistencyAtRevision",
    "ConsistencyLatestAtStart",
    "ConsistencySinceRevision",
    "Cost",
    "DataClassSet",
    "EvalMode",
    "EvalModeDryRun",
    "EvalModeExecute",
    "EvalModeReplay",
    "EvalModeRequireCached",
    "FailureMode",
    "InfoRef",
    "LeavenValue",
    "MetadataBag",
    "OperationReceipt",
    "OutputRecord",
    "PlanDocument",
    "PlanError",
    "PlanOp",
    "PlanResultDocument",
    "ProposalEffect",
    "ProposeRequest",
    "ReceiptRef",
    "Redaction",
    "ReflectionResult",
    "Replayability",
    "RunnerRequest",
    "StageEffectReceipt",
    "StageProposalReceipt",
    "StageRunKind",
    "StageRunPayload",
    "StageRunRequest",
    "StageRunResult",
    "StaleWritePolicy",
    "SurfaceSuggestion",
    "TraceRef",
    "VisibilityClass",
    "WireJsonField",
    "WireJsonLeafArray",
    "WireJsonLeafObject",
    "WireJsonObject",
    "WireJsonScalar",
]
