"""Generated top-level public-seam payload records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

# ruff: noqa: F401, I001

from typing import Literal

from msgspec import UNSET, Struct, UnsetType, field

from .calls import CapabilityCall
from .expressions import PlanExpression, Precondition, ValidationReceipt
from .graph_rows import (
    AssessmentSummaryGraphRow,
    CandidateArtifactSummary,
    CandidateCaseScore,
    CandidateScoresSummary,
    CandidateSummaryGraphRow,
    EventSummaryGraphRow,
    ExtensionGraphRow,
    GraphExtensionBlobRefPayload,
    GraphExtensionPayload,
    GraphExtensionSummaryPayload,
    GraphRow,
    OutputRecord,
    ProposalEffectSummary,
    ProposalEffectSummaryKind,
    ProposalSummaryGraphRow,
    Score,
    VisibilityClass,
)
from .refs import (
    AssessmentRef,
    AssessmentRefRecord,
    AssessmentsSubmittedEventPayload,
    BlobRef,
    CandidateRef,
    CandidateRefRecord,
    CaseRef,
    CaseRefRecord,
    DataClassSet,
    EvaluationAttemptRef,
    EvaluationAttemptRefRecord,
    EvaluationRequestRef,
    EvaluationRequestRefRecord,
    EvaluationRequestedEventPayload,
    EventEmittedSummaryPayload,
    EventSummaryPayload,
    ExternalEventPayload,
    ExternalInfoRefRecord,
    InfoRef,
    MetadataBag,
    ProposalBatchAppliedEventPayload,
    ProposalBatchRef,
    ProposalBatchRefRecord,
    ProposalBatchSubmittedEventPayload,
    ProposalRef,
    ProposalRefRecord,
    ReceiptRef,
    ReceiptRefRecord,
    RunContextSummaryEventPayload,
    TraceRef,
    TraceRefRecord,
    TraceVisibility,
    WireJsonCaseInput,
    WireJsonField,
    WireJsonLeafArray,
    WireJsonLeafObject,
    WireJsonObject,
    WireJsonOutputValue,
    WireJsonScalar,
    WorkspaceRef,
    WorkspaceRefRecord,
)
from .writes import GraphWrite

PLAN_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_6ecf73476db81c5a7412b6831bce68ce0273c295eee827856042207117e2cd48"
)
PLAN_RESULT_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_51fcd2b973fdb5ec3936e09607bac98ad9d733d91de9491f5cdd10c11761d000"
)
STAGE_RUN_SCHEMA_FINGERPRINT = (
    "fp_schema_sha256_da2d026c060b655ea39850dbd43034e097260eefb88a3667207343fb6353a7ec"
)


type Replayability = Literal[
    "pure_read",
    "fully_managed",
    "boundary_managed",
    "has_declared_external_effects",
    "has_untracked_external_effects",
]


class ConsistencyLatestAtStart(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="latest_at_start",
    tag_field="kind",
):
    pass


class ConsistencyAtRevision(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="at_revision",
    tag_field="kind",
):
    revision: str


class ConsistencySinceRevision(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="since_revision",
    tag_field="kind",
):
    since: str
    until: str | UnsetType = UNSET


type Consistency = ConsistencyLatestAtStart | ConsistencyAtRevision | ConsistencySinceRevision


class EvalModeExecute(Struct, frozen=True, forbid_unknown_fields=True, tag="execute", tag_field="kind"):
    pass


class EvalModeDryRun(Struct, frozen=True, forbid_unknown_fields=True, tag="dry_run", tag_field="kind"):
    pass


class EvalModeRequireCached(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="require_cached",
    tag_field="kind",
):
    pass


class EvalModeReplay(Struct, frozen=True, forbid_unknown_fields=True, tag="replay", tag_field="kind"):
    receipts: list[ReceiptRef]


type EvalMode = EvalModeExecute | EvalModeDryRun | EvalModeRequireCached | EvalModeReplay


class CommitPolicyNoGraphWrites(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="no_graph_writes",
    tag_field="kind",
):
    pass


type StaleWritePolicy = Literal["reject", "allow_if_policy_allows", "rebase_extension"]


class CommitPolicyGraphWritesAtomic(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="graph_writes_atomic",
    tag_field="kind",
):
    on_stale: StaleWritePolicy


class CommitPolicyGraphWritesSequential(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="graph_writes_sequential",
    tag_field="kind",
):
    on_failure: Literal["stop", "continue"]
    on_stale: StaleWritePolicy


type CommitPolicy = (
    CommitPolicyNoGraphWrites | CommitPolicyGraphWritesAtomic | CommitPolicyGraphWritesSequential
)
type PlanDeps = list[str]
type PlanOpKind = Literal["let", "call", "write"]
type PlanWriteKind = Literal[
    "submit_proposal_batch",
    "submit_assessments",
    "request_evaluation",
    "apply_proposal_batch",
    "emit_run_event",
]


class PlanOp(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, kw_only=True):
    kind: PlanOpKind
    name: str
    expr: PlanExpression | UnsetType = UNSET
    call: CapabilityCall | UnsetType = UNSET
    write: GraphWrite | UnsetType = UNSET
    idempotency_key: str | UnsetType = UNSET
    preconditions: list[Precondition] | UnsetType = UNSET
    deps: PlanDeps | UnsetType = UNSET


class Cost(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    usd_micro: int | UnsetType = UNSET
    input_tokens: int | UnsetType = UNSET
    output_tokens: int | UnsetType = UNSET
    lm_calls: int | UnsetType = UNSET
    agent_calls: int | UnsetType = UNSET
    sandbox_calls: int | UnsetType = UNSET
    metric_calls: int | UnsetType = UNSET
    wall_ms: int | UnsetType = UNSET


class Redaction(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    path: str
    reason: str
    policy_fingerprint: str | UnsetType = UNSET
    public_reason: str | UnsetType = UNSET
    audit_reason: str | UnsetType = UNSET


type PlanErrorCode = Literal[
    "token_invalid",
    "token_expired",
    "token_revoked",
    "capability_denied",
    "budget_exceeded",
    "quota_exceeded",
    "hidden_partition_violation",
    "data_class_violation",
    "schema_validation_failed",
    "stage_runtime_error",
    "precondition_failed",
    "revision_stale",
    "rate_limited",
    "cancelled",
    "timeout",
    "provider_policy_denied",
    "provider_error",
    "workspace_policy_denied",
    "path_denied",
    "sandbox_denied",
    "watch_closed",
    "internal_error",
    "extension_error",
]


class PlanErrorDetailsObject(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    summary: str | UnsetType = UNSET
    reason: str | UnsetType = UNSET
    retry_after_ms: int | UnsetType = UNSET

    def __post_init__(self) -> None:
        if self.summary is UNSET and self.reason is UNSET and self.retry_after_ms is UNSET:
            raise ValueError("PlanError.details object must carry a typed detail field")


type PlanErrorDetails = str | PlanErrorDetailsObject


class PlanError(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    code: PlanErrorCode
    message: str
    op: str | UnsetType = UNSET
    path: str | UnsetType = UNSET
    receipt: ReceiptRef | UnsetType = UNSET
    retryable: bool | UnsetType = UNSET
    details: PlanErrorDetails | UnsetType = UNSET


class StageCost(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    usd_micro: int | UnsetType = UNSET
    input_tokens: int | UnsetType = UNSET
    output_tokens: int | UnsetType = UNSET
    lm_calls: int | UnsetType = UNSET


class StageEffectBlobContent(Struct, frozen=True, forbid_unknown_fields=True):
    blob_ref: BlobRef
    content_base64: str


class StageEffectReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    method: Literal["leaven/lm.complete", "leaven/agent.run"]
    receipt: str
    call_kind: Literal["lm_complete", "agent_run"] | UnsetType = UNSET
    cost: StageCost | UnsetType = UNSET
    blob_refs: list[BlobRef] | UnsetType = UNSET
    blob_contents: list[StageEffectBlobContent] | UnsetType = UNSET


class StageProposalReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    method: Literal["leaven/proposal.submit_batch"]
    receipt: ReceiptRef
    write_kind: Literal["submit_proposal_batch"] | UnsetType = UNSET
    proposal_ids: list[str] | UnsetType = UNSET


class FailureMode(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    label: str
    description: str
    severity: Literal["low", "medium", "high", "blocking"] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET


class SurfaceSuggestion(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    surface_fingerprint: str
    diagnosis: str
    part_label: str | UnsetType = UNSET
    suggested_direction: str | UnsetType = UNSET
    constraints: list[str] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET


class ReflectionResult(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="reflection_result",
    tag_field="role",
):
    schema_version: Literal["leaven.stage_payloads.v1"]
    summary: str
    source_refs: list[InfoRef]
    read_receipts: list[ReceiptRef]
    data_classes: DataClassSet
    failure_modes: list[FailureMode] | UnsetType = UNSET
    surface_suggestions: list[SurfaceSuggestion] | UnsetType = UNSET
    negative_constraints: list[str] | UnsetType = UNSET
    positive_constraints: list[str] | UnsetType = UNSET
    confidence: float | UnsetType = UNSET


class RunnerRequest(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    tag="runner",
    tag_field="role",
):
    schema_version: Literal["leaven.stage_payloads.v1"]
    run: str
    stage_call_id: str
    candidate: CandidateRef
    case: CaseRef
    case_input: WireJsonCaseInput
    target_forbidden: bool
    capability_fingerprint: str


type ProposalEffect = Literal[
    "create",
    "change",
    "change_from_workspace_diff",
    "change_from_agent_session",
]


class ProposeRequest(
    Struct,
    frozen=True,
    forbid_unknown_fields=True,
    omit_defaults=True,
    tag="proposer",
    tag_field="role",
):
    schema_version: Literal["leaven.stage_payloads.v1"]
    run: str
    stage_call_id: str
    base_revision: str
    parent: CandidateRef
    reflection_result: ReflectionResult
    allowed_effects: list[ProposalEffect]
    capability_fingerprint: str
    surface_fingerprint: str | UnsetType = UNSET
    allowed_change_schemas: list[str] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET
    query_policy_fingerprint: str | UnsetType = UNSET


type StageRunPayload = RunnerRequest | ProposeRequest
type PlanResultStatus = Literal["succeeded", "failed", "cancelled", "timeout"]
type LeavenValueKind = Literal[
    "emit_run_event",
    "graph_set",
    "case_record",
    "workspace_handle",
    "workspace_snapshot",
    "workspace_file",
    "workspace_diff",
    "workspace_listing",
    "lm_response",
    "agent_session",
    "sandbox_exec",
    "proposal_batch_receipt",
    "assessment_batch_receipt",
    "evaluation_request_receipt",
    "apply_receipt",
]
type OperationReceiptKind = Literal["query", "call", "write"]
type CallReceiptKind = Literal[
    "lm_complete", "agent_run", "sandbox_exec", "workspace_materialize", "workspace_release", "extension"
]
type WriteReceiptKind = Literal[
    "submit_proposal_batch",
    "submit_assessments",
    "request_evaluation",
    "apply_proposal_batch",
    "emit_run_event",
]


class LeavenValue(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, kw_only=True):
    kind: LeavenValueKind
    graph_revision: str
    data_classes: DataClassSet
    replayability: Replayability
    receipt: ReceiptRef | UnsetType = UNSET
    event_id: str | UnsetType = UNSET
    items: list[GraphRow] | UnsetType = UNSET
    case: CaseRef | UnsetType = UNSET
    workspace: str | UnsetType = UNSET
    path: str | UnsetType = UNSET
    status: str | UnsetType = UNSET
    proposal_ids: list[str] | UnsetType = UNSET
    assessment_ids: list[str] | UnsetType = UNSET
    evaluation_request_id: str | UnsetType = UNSET
    created_candidates: list[ReceiptRef] | UnsetType = UNSET
    redactions: list[Redaction] | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET


class OperationReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, kw_only=True):
    kind: OperationReceiptKind
    receipt: ReceiptRef
    status: PlanResultStatus
    op_var: str | UnsetType = UNSET
    started_at: str | UnsetType = UNSET
    completed_at: str | UnsetType = UNSET
    error: PlanError | UnsetType = UNSET
    trace_refs: list[TraceRef] | UnsetType = UNSET
    op_hash: str | UnsetType = UNSET
    result_hash: str
    graph_revision: str | UnsetType = UNSET
    read_scope_fingerprint: str | UnsetType = UNSET
    projection_fingerprint: str | UnsetType = UNSET
    source_refs: list[InfoRef] | UnsetType = UNSET
    bytes: int | UnsetType = UNSET
    call_kind: CallReceiptKind | UnsetType = UNSET
    request_hash: str | UnsetType = UNSET
    runtime_fingerprint: str | UnsetType = UNSET
    cost: Cost | UnsetType = UNSET
    charge_receipts: list[str] | UnsetType = UNSET
    write_kind: WriteReceiptKind | UnsetType = UNSET
    base_revision: str | UnsetType = UNSET
    committed_revision: str | UnsetType = UNSET
    proposal_batch_id: str | UnsetType = UNSET
    proposal_ids: list[str] | UnsetType = UNSET
    evaluation_request_id: str | UnsetType = UNSET
    assessment_ids: list[str] | UnsetType = UNSET
    created_candidates: list[ReceiptRef] | UnsetType = UNSET
    event_id: str | UnsetType = UNSET
    preconditions: list[Precondition] | UnsetType = UNSET
    validation_receipts: list[ValidationReceipt] | UnsetType = UNSET


class ChargeReceipt(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    receipt: str
    source_receipt: ReceiptRef
    cost: Cost
    charged_at: str
    ledger_scope: str | UnsetType = UNSET


class PlanDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    schema_version: Literal["leaven.plan.v1"]
    plan_id: str
    consistency: Consistency
    mode: EvalMode
    ops: list[PlanOp]
    return_: list[str] = field(name="return")
    commit: CommitPolicy
    metadata: MetadataBag | UnsetType = UNSET


class PlanResultDocument(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    schema_version: Literal["leaven.plan_result.v1"]
    plan_id: str
    capability_fingerprint: str
    policy_fingerprint: str
    base_revision: str
    final_revision: str
    replayability_summary: Replayability
    values: dict[str, LeavenValue]
    receipts: list[OperationReceipt]
    redactions: list[Redaction]
    charges: list[ChargeReceipt]
    errors: list[PlanError]
    metadata: MetadataBag | UnsetType = UNSET


type StageRunKind = Literal["runner"] | Literal["proposer"]


class StageRunRequest(Struct, frozen=True, forbid_unknown_fields=True):
    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_request"]
    stage: StageRunKind
    payload: StageRunPayload


class StageRunResult(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    schema_version: Literal["leaven.stage_run.v1"]
    message: Literal["stage_run_result"]
    stage: StageRunKind
    stage_call_id: str
    output: OutputRecord
    effect_receipts: list[StageEffectReceipt] | UnsetType = UNSET
    proposal_receipts: list[StageProposalReceipt] | UnsetType = UNSET


__all__ = (  # noqa: PLE0605, SIM905
    "PLAN_RESULT_SCHEMA_FINGERPRINT PLAN_SCHEMA_FINGERPRINT STAGE_RUN_SCHEMA_FINGERPRINT "
    "AssessmentRef AssessmentRefRecord AssessmentsSubmittedEventPayload BlobRef CandidateRef CandidateRefRecord CaseRef CaseRefRecord EvaluationAttemptRef EvaluationAttemptRefRecord EvaluationRequestRef EvaluationRequestRefRecord EvaluationRequestedEventPayload EventEmittedSummaryPayload EventSummaryPayload ExternalEventPayload ExternalInfoRefRecord InfoRef ProposalBatchAppliedEventPayload ProposalBatchRef ProposalBatchRefRecord ProposalBatchSubmittedEventPayload ProposalRef ProposalRefRecord ReceiptRef RunContextSummaryEventPayload ReceiptRefRecord TraceRef TraceRefRecord TraceVisibility WorkspaceRef WorkspaceRefRecord "
    "AssessmentSummaryGraphRow CandidateArtifactSummary CandidateCaseScore CandidateScoresSummary CandidateSummaryGraphRow CapabilityCall ChargeReceipt CommitPolicy CommitPolicyGraphWritesAtomic "
    "CommitPolicyGraphWritesSequential CommitPolicyNoGraphWrites Consistency ConsistencyAtRevision "
    "ConsistencyLatestAtStart ConsistencySinceRevision Cost DataClassSet EvalMode EvalModeDryRun "
    "EvalModeExecute EvalModeReplay EvalModeRequireCached EventSummaryGraphRow ExtensionGraphRow FailureMode "
    "GraphExtensionBlobRefPayload GraphExtensionPayload GraphExtensionSummaryPayload GraphRow GraphWrite InfoRef LeavenValue MetadataBag OperationReceipt OutputRecord PlanDocument PlanExpression Precondition "
    "PlanError PlanErrorCode PlanErrorDetails PlanErrorDetailsObject PlanOp PlanResultDocument ProposalBatchRef ProposalBatchRefRecord ProposalEffect ProposeRequest "
    "ProposalEffectSummary ProposalEffectSummaryKind ProposalRef ProposalRefRecord ProposalSummaryGraphRow ReceiptRef Redaction ReflectionResult Replayability "
    "RunnerRequest Score "
    "StageEffectReceipt StageProposalReceipt StageRunKind StageRunPayload StageRunRequest StageRunResult "
    "StaleWritePolicy SurfaceSuggestion TraceRef ValidationReceipt VisibilityClass WireJsonField WireJsonLeafArray "
    "WireJsonLeafObject WireJsonObject WireJsonScalar"
).split()
