"""Generated public-seam Plan graph-write records.

Generated by `codegen/generate_seam_wire.py`; do not edit by hand.
"""

from typing import Literal

from msgspec import UNSET, Struct, UnsetType

from .expressions import PlanExpression, ValueExpr
from .refs import (
    CandidateRef,
    MetadataBag,
    ProposalBatchRef,
    ReceiptRef,
    WireJsonField,
    WireJsonObject,
    WorkspaceRef,
)


class ProposalEffectCreate(Struct, frozen=True, forbid_unknown_fields=True, tag="create", tag_field="kind"):
    artifact_type: str
    artifact_schema: str
    artifact: ValueExpr


class ProposalEffectChange(Struct, frozen=True, forbid_unknown_fields=True, tag="change", tag_field="kind"):
    target: CandidateRef
    surface_fingerprint: str
    change_schema: str
    change: ValueExpr


class ProposalEffectWorkspaceDiff(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="change_from_workspace_diff", tag_field="kind"):
    target: CandidateRef
    workspace: WorkspaceRef
    surface_fingerprint: str
    change_schema: str
    roots: list[str] | UnsetType = UNSET
    parser: str | UnsetType = UNSET


class ProposalEffectAgentSession(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True, tag="change_from_agent_session", tag_field="kind"):
    target: CandidateRef
    agent_receipt: ReceiptRef
    parser: str
    surface_fingerprint: str
    change_schema: str


type ProposalEffectWrite = (
    ProposalEffectCreate
    | ProposalEffectChange
    | ProposalEffectWorkspaceDiff
    | ProposalEffectAgentSession
)


class ProposalWriteRecord(Struct, frozen=True, forbid_unknown_fields=True, omit_defaults=True):
    effect: ProposalEffectWrite
    causal: WireJsonObject
    informed_by: PlanExpression
    annotations: ValueExpr | UnsetType = UNSET
    annotations_schema: str | UnsetType = UNSET
    read_receipts: list[ReceiptRef] | UnsetType = UNSET
    metadata: MetadataBag | UnsetType = UNSET


class SubmitProposalBatchWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="submit_proposal_batch", tag_field="kind"):
    semantics: Literal["alternatives", "sequence"]
    proposals: list[ProposalWriteRecord]


class SubmitAssessmentsWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="submit_assessments", tag_field="kind"):
    evaluation_request_id: str
    assessments: list[WireJsonObject]


class RequestEvaluationWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="request_evaluation", tag_field="kind"):
    request: WireJsonObject


class ApplyProposalBatchWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="apply_proposal_batch", tag_field="kind"):
    proposal_batch: ProposalBatchRef
    policy: Literal["apply_all", "apply_first_valid", "apply_by_optimizer_policy"]


class EmitRunEventWrite(Struct, frozen=True, forbid_unknown_fields=True, tag="emit_run_event", tag_field="kind"):
    event_kind: str
    payload_schema: str
    payload: WireJsonField
    visibility: str


type GraphWrite = (
    SubmitProposalBatchWrite
    | SubmitAssessmentsWrite
    | RequestEvaluationWrite
    | ApplyProposalBatchWrite
    | EmitRunEventWrite
)


__all__ = (  # noqa: PLE0605, SIM905
    "ApplyProposalBatchWrite EmitRunEventWrite GraphWrite ProposalEffectAgentSession ProposalEffectChange ProposalEffectCreate ProposalEffectWorkspaceDiff ProposalEffectWrite ProposalWriteRecord RequestEvaluationWrite SubmitAssessmentsWrite SubmitProposalBatchWrite"
).split()
